generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfguarduser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sfguarduser
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Liste des utilisateurs
        display: [Username,first_name,last_name,email_address,Salt]
      filter:
        class: false
      form:    ~
      edit:
        title: Editer un utilisateur
      new:
        title: Créer un utilisateur
