<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/09 10:50:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ashile',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
