<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/08 17:22:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ashile',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
