<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/06/09 10:49:47
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 'acad',
    ),
  ),
);
