<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/06/08 17:22:37
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 'acad',
    ),
  ),
);
