<?php
// auto-generated by sfViewConfigHandler
// date: 2015/06/09 10:49:47
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'ash', false, false);
  $response->addMeta('description', 'gestion et suivit  des scolarisations de eleves handicapes de la reunion', false, false);
  $response->addMeta('keywords', 'ash, enfance, handicap, academie de la reunion', false, false);
  $response->addMeta('language', 'fr', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('thickbox.css', '', array ());
  $response->addStylesheet('radmenu.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('jquery-ui-1.8.21.custom.css', '', array ());
  $response->addStylesheet('menu.css', '', array ());
  $response->addStylesheet('data_table.css', '', array ());
  $response->addStylesheet('datatable_jui.css', '', array ());
  $response->addStylesheet('basic.css', '', array ());
  $response->addStylesheet('basic_ie.css', '', array ());
  $response->addJavascript('thickbox-compressed.js', '', array ());
  $response->addJavascript('radmenu.js', '', array ());
  $response->addJavascript('oXHR.js', '', array ());
  $response->addJavascript('prototype.js', '', array ());
  $response->addJavascript('jquery-1.4.3.min.js', '', array ());
  $response->addJavascript('jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.21.custom.min.js', '', array ());
  $response->addJavascript('jquery.ui.datepicker-fr.js', '', array ());
  $response->addJavascript('jquery.dataTables.min.js', '', array ());
  $response->addJavascript('basic.js', '', array ());
  $response->addJavascript('jquery.simplemodal.js', '', array ());
  $response->addJavascript('jsProgressBarHandler.js', '', array ());
  $response->addJavascript('scriptaculous.js?load=effects', '', array ());
  $response->addJavascript('modalbox.js', '', array ());
  $response->addJavascript('orientation.js', '', array ());
  $response->addJavascript('tuteur.js', '', array ());
  $response->addJavascript('modmonsco.js', '', array ());


