<?php

/**
 * BaseSecteurEtabsco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etabsco_id
 * @property integer $secteur_id
 * @property Secteur $Secteur
 * @property Etabsco $Etabsco
 * 
 * @method integer        getEtabscoId()  Returns the current record's "etabsco_id" value
 * @method integer        getSecteurId()  Returns the current record's "secteur_id" value
 * @method Secteur        getSecteur()    Returns the current record's "Secteur" value
 * @method Etabsco        getEtabsco()    Returns the current record's "Etabsco" value
 * @method SecteurEtabsco setEtabscoId()  Sets the current record's "etabsco_id" value
 * @method SecteurEtabsco setSecteurId()  Sets the current record's "secteur_id" value
 * @method SecteurEtabsco setSecteur()    Sets the current record's "Secteur" value
 * @method SecteurEtabsco setEtabsco()    Sets the current record's "Etabsco" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSecteurEtabsco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('secteur_etabsco');
        $this->hasColumn('etabsco_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('secteur_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Secteur', array(
             'local' => 'secteur_id',
             'foreign' => 'id'));

        $this->hasOne('Etabsco', array(
             'local' => 'etabsco_id',
             'foreign' => 'id'));
    }
}