<?php

/**
 * BaseMessageAccueil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $contenu
 * 
 * @method clob           getContenu() Returns the current record's "contenu" value
 * @method MessageAccueil setContenu() Sets the current record's "contenu" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessageAccueil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message_accueil');
        $this->hasColumn('contenu', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}