<?php

/**
 * BaseTypeReunion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelletypereunion
 * @property Doctrine_Collection $Reunions
 * 
 * @method string              getLibelletypereunion() Returns the current record's "libelletypereunion" value
 * @method Doctrine_Collection getReunions()           Returns the current record's "Reunions" collection
 * @method TypeReunion         setLibelletypereunion() Sets the current record's "libelletypereunion" value
 * @method TypeReunion         setReunions()           Sets the current record's "Reunions" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeReunion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_reunion');
        $this->hasColumn('libelletypereunion', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reunion as Reunions', array(
             'local' => 'id',
             'foreign' => 'typereunion_id'));
    }
}