<?php

/**
 * BaseConditionsuspensive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $conditionsuspensive
 * @property Doctrine_Collection $DemandeAvss
 * 
 * @method string              getConditionsuspensive() Returns the current record's "conditionsuspensive" value
 * @method Doctrine_Collection getDemandeAvss()         Returns the current record's "DemandeAvss" collection
 * @method Conditionsuspensive setConditionsuspensive() Sets the current record's "conditionsuspensive" value
 * @method Conditionsuspensive setDemandeAvss()         Sets the current record's "DemandeAvss" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConditionsuspensive extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conditionsuspensive');
        $this->hasColumn('conditionsuspensive', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeAvs as DemandeAvss', array(
             'local' => 'id',
             'foreign' => 'conditionsuspensive_id'));
    }
}