<?php

/**
 * BaseDirecteurEtab
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Etabscos
 * 
 * @method Doctrine_Collection getEtabscos() Returns the current record's "Etabscos" collection
 * @method DirecteurEtab       setEtabscos() Sets the current record's "Etabscos" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDirecteurEtab extends Personne
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('directeur_etab');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Etabsco as Etabscos', array(
             'local' => 'id',
             'foreign' => 'directeuretab_id'));
    }
}