<?php

/**
 * BaseCommune
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom_commune
 * @property Doctrine_Collection $Quartiers
 * 
 * @method string              getNomCommune()  Returns the current record's "nom_commune" value
 * @method Doctrine_Collection getQuartiers()   Returns the current record's "Quartiers" collection
 * @method Commune             setNomCommune()  Sets the current record's "nom_commune" value
 * @method Commune             setQuartiers()   Sets the current record's "Quartiers" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommune extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commune');
        $this->hasColumn('nom_commune', 'string', 70, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 70,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Quartier as Quartiers', array(
             'local' => 'id',
             'foreign' => 'commune_id'));
    }
}