<?php

/**
 * BaseDemandeOrientation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mdph_id
 * @property integer $classeext_id
 * @property integer $demijournee_id
 * @property date $date_demande_orientation
 * @property date $datedebutnotif
 * @property date $datefinnotif
 * @property date $datedecisioncda
 * @property boolean $decisioncda
 * @property boolean $traite
 * @property boolean $etat
 * @property clob $notes
 * @property Classeext $Classeext
 * @property Demijournee $Demijournee
 * @property Mdph $Mdph
 * 
 * @method integer            getMdphId()                   Returns the current record's "mdph_id" value
 * @method integer            getClasseextId()              Returns the current record's "classeext_id" value
 * @method integer            getDemijourneeId()            Returns the current record's "demijournee_id" value
 * @method date               getDateDemandeOrientation()   Returns the current record's "date_demande_orientation" value
 * @method date               getDatedebutnotif()           Returns the current record's "datedebutnotif" value
 * @method date               getDatefinnotif()             Returns the current record's "datefinnotif" value
 * @method date               getDatedecisioncda()          Returns the current record's "datedecisioncda" value
 * @method boolean            getDecisioncda()              Returns the current record's "decisioncda" value
 * @method boolean            getTraite()                   Returns the current record's "traite" value
 * @method boolean            getEtat()                     Returns the current record's "etat" value
 * @method clob               getNotes()                    Returns the current record's "notes" value
 * @method Classeext          getClasseext()                Returns the current record's "Classeext" value
 * @method Demijournee        getDemijournee()              Returns the current record's "Demijournee" value
 * @method Mdph               getMdph()                     Returns the current record's "Mdph" value
 * @method DemandeOrientation setMdphId()                   Sets the current record's "mdph_id" value
 * @method DemandeOrientation setClasseextId()              Sets the current record's "classeext_id" value
 * @method DemandeOrientation setDemijourneeId()            Sets the current record's "demijournee_id" value
 * @method DemandeOrientation setDateDemandeOrientation()   Sets the current record's "date_demande_orientation" value
 * @method DemandeOrientation setDatedebutnotif()           Sets the current record's "datedebutnotif" value
 * @method DemandeOrientation setDatefinnotif()             Sets the current record's "datefinnotif" value
 * @method DemandeOrientation setDatedecisioncda()          Sets the current record's "datedecisioncda" value
 * @method DemandeOrientation setDecisioncda()              Sets the current record's "decisioncda" value
 * @method DemandeOrientation setTraite()                   Sets the current record's "traite" value
 * @method DemandeOrientation setEtat()                     Sets the current record's "etat" value
 * @method DemandeOrientation setNotes()                    Sets the current record's "notes" value
 * @method DemandeOrientation setClasseext()                Sets the current record's "Classeext" value
 * @method DemandeOrientation setDemijournee()              Sets the current record's "Demijournee" value
 * @method DemandeOrientation setMdph()                     Sets the current record's "Mdph" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDemandeOrientation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('demande_orientation');
        $this->hasColumn('mdph_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('classeext_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('demijournee_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_demande_orientation', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datedebutnotif', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefinnotif', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datedecisioncda', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('decisioncda', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('traite', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('etat', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('notes', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Classeext', array(
             'local' => 'classeext_id',
             'foreign' => 'id'));

        $this->hasOne('Demijournee', array(
             'local' => 'demijournee_id',
             'foreign' => 'id'));

        $this->hasOne('Mdph', array(
             'local' => 'mdph_id',
             'foreign' => 'id',
             'owningSide' => true));
    }
}