<?php

/**
 * BaseTypeContratAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $typecontrat
 * @property Doctrine_Collection $ContratAvss
 * @property boolean $affichage
 * 
 * @method string              getTypecontrat() Returns the current record's "typecontrat" value
 * @method Doctrine_Collection getContratAvss() Returns the current record's "ContratAvss" collection
 * @method boolean             getAffichage()   Returns the current record's "affichage" value
 * @method TypeContratAvs      setTypecontrat() Sets the current record's "typecontrat" value
 * @method TypeContratAvs      setContratAvss() Sets the current record's "ContratAvss" collection
 * @method TypeContratAvs      setAffichage() Sets the current record's "affichage" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeContratAvs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_contrat_avs');
        $this->hasColumn('typecontrat', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
		$this->hasColumn('affichage', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ContratAvs as ContratAvss', array(
             'local' => 'id',
             'foreign' => 'typecontratavs_id'));
    }
}