<?php

/**
 * BaseSpecialite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libellespecialite
 * @property Doctrine_Collection $Bilans
 * @property Doctrine_Collection $Specialistes
 * 
 * @method string              getLibellespecialite() Returns the current record's "libellespecialite" value
 * @method Doctrine_Collection getBilans()            Returns the current record's "Bilans" collection
 * @method Doctrine_Collection getSpecialistes()      Returns the current record's "Specialistes" collection
 * @method Specialite          setLibellespecialite() Sets the current record's "libellespecialite" value
 * @method Specialite          setBilans()            Sets the current record's "Bilans" collection
 * @method Specialite          setSpecialistes()      Sets the current record's "Specialistes" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpecialite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('specialite');
        $this->hasColumn('libellespecialite', 'string', 70, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 70,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bilan as Bilans', array(
             'local' => 'id',
             'foreign' => 'specialite_id'));
			 
		$this->hasMany('SuivitExterne as SuivitExternes', array(
             'local' => 'id',
             'foreign' => 'specialite_id'));

        $this->hasMany('Specialiste as Specialistes', array(
             'local' => 'id',
             'foreign' => 'specialite_id'));
    }
}