<?php

/**
 * BaseEleveAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eleve_id
 * @property integer $avs_id
 * @property clob $commentaire
 * @property integer $quotitehorraireavs
 * @property date $datedebut
 * @property date $datefin
 * @property Avs $Avs
 * @property Eleve $Eleve
 * @property Orientation $Orientation
 * 
 * @method integer     getEleveId()            Returns the current record's "eleve_id" value
 * @method integer     getAvsId()              Returns the current record's "avs_id" value
 * @method clob        getCommentaire()        Returns the current record's "commentaire" value
 * @method integer     getQuotitehorraireavs() Returns the current record's "quotitehorraireavs" value
 * @method date        getDatedebut()          Returns the current record's "datedebut" value
 * @method date        getDatefin()            Returns the current record's "datefin" value
 * @method Avs         getAvs()                Returns the current record's "Avs" value
 * @method Eleve       getEleve()              Returns the current record's "Eleve" value
 * @method Orientation getOrientation()        Returns the current record's "Orientation" value
 * @method EleveAvs    setEleveId()            Sets the current record's "eleve_id" value
 * @method EleveAvs    setAvsId()              Sets the current record's "avs_id" value
 * @method EleveAvs    setCommentaire()        Sets the current record's "commentaire" value
 * @method EleveAvs    setQuotitehorraireavs() Sets the current record's "quotitehorraireavs" value
 * @method EleveAvs    setDatedebut()          Sets the current record's "datedebut" value
 * @method EleveAvs    setDatefin()            Sets the current record's "datefin" value
 * @method EleveAvs    setAvs()                Sets the current record's "Avs" value
 * @method EleveAvs    setEleve()              Sets the current record's "Eleve" value
 * @method EleveAvs    setOrientation()        Sets the current record's "Orientation" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEleveAvs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eleve_avs');
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             ));
        $this->hasColumn('avs_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             ));
        $this->hasColumn('commentaire', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('quotitehorraireavs', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('datedebut', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Avs', array(
             'local' => 'avs_id',
             'foreign' => 'id'));

        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));

        $this->hasOne('Orientation', array(
             'local' => 'eleve_id',
             'foreign' => 'eleve_id'));
    }
}