<?php

/**
 * BaseFournisseur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nomfournisseur
 * @property string $faxfournisseur
 * @property string $telfournisseur
 * @property string $adressefournisseurbat
 * @property string $adressefournisseurrue
 * @property string $codepostalfournisseur
 * @property string $villefournisseur
 * @property Doctrine_Collection $Commandes
 * @property Doctrine_Collection $Materiels
 * 
 * @method string              getNomfournisseur()        Returns the current record's "nomfournisseur" value
 * @method string              getFaxfournisseur()        Returns the current record's "faxfournisseur" value
 * @method string              getTelfournisseur()        Returns the current record's "telfournisseur" value
 * @method string              getAdressefournisseurbat() Returns the current record's "adressefournisseurbat" value
 * @method string              getAdressefournisseurrue() Returns the current record's "adressefournisseurrue" value
 * @method string              getCodepostalfournisseur() Returns the current record's "codepostalfournisseur" value
 * @method string              getVillefournisseur()      Returns the current record's "villefournisseur" value
 * @method Doctrine_Collection getCommandes()             Returns the current record's "Commandes" collection
 * @method Doctrine_Collection getMateriels()             Returns the current record's "Materiels" collection
 * @method Fournisseur         setNomfournisseur()        Sets the current record's "nomfournisseur" value
 * @method Fournisseur         setFaxfournisseur()        Sets the current record's "faxfournisseur" value
 * @method Fournisseur         setTelfournisseur()        Sets the current record's "telfournisseur" value
 * @method Fournisseur         setAdressefournisseurbat() Sets the current record's "adressefournisseurbat" value
 * @method Fournisseur         setAdressefournisseurrue() Sets the current record's "adressefournisseurrue" value
 * @method Fournisseur         setCodepostalfournisseur() Sets the current record's "codepostalfournisseur" value
 * @method Fournisseur         setVillefournisseur()      Sets the current record's "villefournisseur" value
 * @method Fournisseur         setCommandes()             Sets the current record's "Commandes" collection
 * @method Fournisseur         setMateriels()             Sets the current record's "Materiels" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFournisseur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fournisseur');
        $this->hasColumn('nomfournisseur', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('faxfournisseur', 'string', 15, array(
             'type' => 'string',
             'regexp' => '/^([\\s]*[0-9]+[\\s]*)+$/',
             'length' => 15,
             ));
        $this->hasColumn('telfournisseur', 'string', 15, array(
             'type' => 'string',
             'regexp' => '/^([\\s]*[0-9]+[\\s]*)+$/',
             'length' => 15,
             ));
        $this->hasColumn('adressefournisseurbat', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('adressefournisseurrue', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('codepostalfournisseur', 'string', 30, array(
             'type' => 'string',
             'regexp' => '/^([\\s]*[0-9]+[\\s]*)+$/',
             'length' => 30,
             ));
        $this->hasColumn('villefournisseur', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Commande as Commandes', array(
             'local' => 'id',
             'foreign' => 'fournisseur_id'));

        $this->hasMany('Materiel as Materiels', array(
             'local' => 'id',
             'foreign' => 'fournisseur_id'));
    }
}