<?php

/**
 * BaseAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $ContratAvss
 * @property Doctrine_Collection $EleveAvss
 * 
 * @method Doctrine_Collection getContratAvss() Returns the current record's "ContratAvss" collection
 * @method Doctrine_Collection getEleveAvss()   Returns the current record's "EleveAvss" collection
 * @method Avs                 setContratAvss() Sets the current record's "ContratAvss" collection
 * @method Avs                 setEleveAvss()   Sets the current record's "EleveAvss" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvs extends Personne
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('avs');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ContratAvs as ContratAvs', array(
             'local' => 'id',
             'foreign' => 'avs_id'));

        $this->hasMany('EleveAvs as EleveAvss', array(
             'local' => 'id',
             'foreign' => 'avs_id'));
    }
}