<?php

/**
 * BaseMdph
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eleve_id
 * @property date $datecreationpps
 * @property integer $nbheuresavs
 * @property date $dateenvoiedossier
 * @property boolean $etat
 * @property date $dateess
 * @property date $datepjdom
 * @property date $datepjident
 * @property date $datebilanmedical
 * @property boolean $depotparent
 * @property Eleve $Eleve
 * @property Doctrine_Collection $Bilans
 * @property Doctrine_Collection $DemandeAvss
 * @property DemandeSessad $DemandeSessads
 * @property DemandeMateriel $DemandeMateriels
 * @property Doctrine_Collection $DemandeOrientations
 * @property Doctrine_Collection $DemandeTransports
 * @property Doctrine_Collection $PiecesDossiers
 * 
 * @method integer             getEleveId()             Returns the current record's "eleve_id" value
 * @method date                getDatecreationpps()     Returns the current record's "datecreationpps" value
 * @method integer             getNbheuresavs()         Returns the current record's "nbheuresavs" value
 * @method date                getDateenvoiedossier()   Returns the current record's "dateenvoiedossier" value
 * @method boolean             getEtat()                Returns the current record's "etat" value
 * @method date                getDateess()             Returns the current record's "dateess" value
 * @method date                getDatepjdom()           Returns the current record's "datepjdom" value
 * @method date                getDatepjident()         Returns the current record's "datepjident" value
 * @method date                getDatebilanmedical()    Returns the current record's "datebilanmedical" value
 * @method boolean             getDepotparent()         Returns the current record's "depotparent" value
 * @method Eleve               getEleve()               Returns the current record's "Eleve" value
 * @method Doctrine_Collection getBilans()              Returns the current record's "Bilans" collection
 * @method Doctrine_Collection getDemandeAvss()         Returns the current record's "DemandeAvss" collection
 * @method DemandeSessad       getDemandeSessads()      Returns the current record's "DemandeSessads" value
 * @method DemandeMateriel     getDemandeMateriels()    Returns the current record's "DemandeMateriels" value
 * @method Doctrine_Collection getDemandeOrientations() Returns the current record's "DemandeOrientations" collection
 * @method Doctrine_Collection getDemandeTransports()   Returns the current record's "DemandeTransports" collection
 * @method Doctrine_Collection getPiecesDossiers()      Returns the current record's "PiecesDossiers" collection
 * @method Mdph                setEleveId()             Sets the current record's "eleve_id" value
 * @method Mdph                setDatecreationpps()     Sets the current record's "datecreationpps" value
 * @method Mdph                setNbheuresavs()         Sets the current record's "nbheuresavs" value
 * @method Mdph                setDateenvoiedossier()   Sets the current record's "dateenvoiedossier" value
 * @method Mdph                setEtat()                Sets the current record's "etat" value
 * @method Mdph                setDateess()             Sets the current record's "dateess" value
 * @method Mdph                setDatepjdom()           Sets the current record's "datepjdom" value
 * @method Mdph                setDatepjident()         Sets the current record's "datepjident" value
 * @method Mdph                setDatebilanmedical()    Sets the current record's "datebilanmedical" value
 * @method Mdph                setDepotparent()         Sets the current record's "depotparent" value
 * @method Mdph                setEleve()               Sets the current record's "Eleve" value
 * @method Mdph                setBilans()              Sets the current record's "Bilans" collection
 * @method Mdph                setDemandeAvss()         Sets the current record's "DemandeAvss" collection
 * @method Mdph                setDemandeSessads()      Sets the current record's "DemandeSessads" value
 * @method Mdph                setDemandeMateriels()    Sets the current record's "DemandeMateriels" value
 * @method Mdph                setDemandeOrientations() Sets the current record's "DemandeOrientations" collection
 * @method Mdph                setDemandeTransports()   Sets the current record's "DemandeTransports" collection
 * @method Mdph                setPiecesDossiers()      Sets the current record's "PiecesDossiers" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMdph extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mdph');
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('datecreationpps', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('nbheuresavs', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dateenvoiedossier', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('etat', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('dateess', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datepjdom', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datepjident', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datebilanmedical', 'date', null, array(
             'type' => 'date',
             ));
		$this->hasColumn('depotparent', 'boolean', null, array(
             'type' => 'boolean',
            
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasMany('Bilan as Bilans', array(
             'local' => 'id',
             'foreign' => 'mdph_id'));

        $this->hasMany('DemandeAvs as DemandeAvss', array(
             'local' => 'id',
             'foreign' => 'mdph_id'));

        $this->hasOne('DemandeSessad as DemandeSessads', array(
             'local' => 'id',
             'foreign' => 'mdph_id'));

        $this->hasOne('DemandeMateriel as DemandeMateriels', array(
             'local' => 'id',
             'foreign' => 'mdph_id'));

        $this->hasMany('DemandeOrientation as DemandeOrientations', array(
             'local' => 'id',
             'foreign' => 'mdph_id'));

        $this->hasMany('DemandeTransport as DemandeTransports', array(
             'local' => 'id',
             'foreign' => 'mdph_id'));

        $this->hasMany('PiecesDossier as PiecesDossiers', array(
             'local' => 'id',
             'foreign' => 'mdph_id'));
    }
}