<?php

/**
 * BaseReponse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $reponse
  * @property string $num_reponse
 * @property string $libelle_reponse
 * @property string $degreetabsco
 * @property integer $question_id
 * @property string $algorithm
 * @property Doctrine_Collection $Question
 * @property Doctrine_Collection $Dgescos
 * 
 * @method string              getReponse()         Returns the current record's "reponse" value
 * @method string              getNumReponse()         Returns the current record's "num_reponse" value
 * @method string              getLibelleReponse()  Returns the current record's "libelle_reponse" value
 * @method string              getDegreetabsco()    Returns the current record's "degreteabsco" value
 * @method integer             getQuestionId()      Returns the current record's "question_id" value
 * @method string              getAlgorithm()       Returns the current record's "algorithm" value
 * @method Doctrine_Collection getQuestion()        Returns the current record's "Question" collection
 * @method Doctrine_Collection getDgescos()         Returns the current record's "Dgescos" collection
 * @method Reponse             setReponse()         Sets the current record's "reponse" value
 * @method Reponse             setNumReponse()      Sets the current record's "num_reponse" value
 * @method Reponse             setDegreetabsco()    Sets the current record's "degreteabsco" value
 * @method Reponse             setLibelleReponse()  Sets the current record's "libelle_reponse" value
 * @method Reponse             setQuestionId()      Sets the current record's "question_id" value
 * @method Reponse             setAlgorithm()       Sets the current record's "algorithm" value
 * @method Reponse             setQuestion()        Sets the current record's "Question" collection
 * @method Reponse             setDgescos()         Sets the current record's "Dgescos" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReponse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reponse');
        $this->hasColumn('reponse', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('libelle_reponse', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
		$this->hasColumn('degreetabsco', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
	    $this->hasColumn('num_reponse', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Question', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $this->hasMany('Dgesco as Dgescos', array(
             'local' => 'id',
             'foreign' => 'reponse_id'));
    }
}