<?php

/**
 * BaseSecteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sfguarduser_id
 * @property string $libellesecteur
 * @property sfGuardUser $sfguarduser
 * @property Doctrine_Collection $Eleves
 * @property Doctrine_Collection $SecteurEtabscos
 * @property Doctrine_Collection $OrganismeSuivits
 * @property Doctrine_Collection $Specialistes
 * 
 * @method integer             getSfguarduserId()    Returns the current record's "sfguarduser_id" value
 * @method string              getLibellesecteur()   Returns the current record's "libellesecteur" value
 * @method sfGuardUser         getSfguarduser()      Returns the current record's "sfguarduser" value
 * @method Doctrine_Collection getEleves()           Returns the current record's "Eleves" collection
 * @method Doctrine_Collection getSecteurEtabscos()  Returns the current record's "SecteurEtabscos" collection
 * @method Doctrine_Collection getOrganismeSuivits() Returns the current record's "OrganismeSuivits" collection
 * @method Doctrine_Collection getSpecialistes()     Returns the current record's "Specialistes" collection
 * @method Secteur             setSfguarduserId()    Sets the current record's "sfguarduser_id" value
 * @method Secteur             setLibellesecteur()   Sets the current record's "libellesecteur" value
 * @method Secteur             setSfguarduser()      Sets the current record's "sfguarduser" value
 * @method Secteur             setEleves()           Sets the current record's "Eleves" collection
 * @method Secteur             setSecteurEtabscos()  Sets the current record's "SecteurEtabscos" collection
 * @method Secteur             setOrganismeSuivits() Sets the current record's "OrganismeSuivits" collection
 * @method Secteur             setSpecialistes()     Sets the current record's "Specialistes" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSecteur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('secteur');
        $this->hasColumn('sfguarduser_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('libellesecteur', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as sfguarduser', array(
             'local' => 'sfguarduser_id',
             'foreign' => 'id'));

        $this->hasMany('Eleve as Eleves', array(
             'local' => 'id',
             'foreign' => 'secteur_id'));

        $this->hasMany('SecteurEtabsco as SecteurEtabscos', array(
             'local' => 'id',
             'foreign' => 'secteur_id'));

        $this->hasMany('OrganismeSuivit as OrganismeSuivits', array(
             'local' => 'id',
             'foreign' => 'secteur_id'));

        $this->hasMany('Specialiste as Specialistes', array(
             'local' => 'id',
             'foreign' => 'secteur_id'));
    }
}