<?php

/**
 * BaseEleve
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quartier_id
 * @property integer $secteur_id
 * @property string $ine
 * @property string $numeromdph
 * @property string $nom
 * @property string $prenom
 * @property date $datenaissance
 * @property string $adresseelevebat
 * @property string $adresseleverue
 * @property clob $notes
 * @property string $sexe
 * @property date $datesortie
 * @property string $motif
 * @property date $etat_acc
 * @property date $etat_mat
 * @property Secteur $Secteur
 * @property Pps $Pps
 * @property Orientation $Orientation
 * @property Quartier $Quartier
 * @property Doctrine_Collection $Dgescos
 * @property Doctrine_Collection $EleveAvss
 * @property Doctrine_Collection $Eleves
 * @property Doctrine_Collection $Mdphs
 * @property Doctrine_Collection $Modnonscos
 * @property Doctrine_Collection $Tuteur
 * @property Doctrine_Collection $Reunions
 * @property Doctrine_Collection $Sessadobtenus
 * @property Doctrine_Collection $SuivitExternes
 * @property Doctrine_Collection $Transportobtenu
 * @property Doctrine_Collection $Mails
 * 
 * @method integer             getQuartierId()      Returns the current record's "quartier_id" value
 * @method integer             getSecteurId()       Returns the current record's "secteur_id" value
 * @method integer             getPpsId()           Returns the current record's "pps_id" value
 * @method string              getIne()             Returns the current record's "ine" value
 * @method string              getNumeromdph()      Returns the current record's "numeromdph" value
 * @method string              getNom()             Returns the current record's "nom" value
 * @method string              getPrenom()          Returns the current record's "prenom" value
 * @method date                getDatenaissance()   Returns the current record's "datenaissance" value
 * @method string              getAdresseelevebat() Returns the current record's "adresseelevebat" value
 * @method string              getAdresseleverue()  Returns the current record's "adresseleverue" value
 * @method clob                getNotes()           Returns the current record's "notes" value
 * @method string              getSexe()            Returns the current record's "sexe" value
 * @method date                getDatesortie()      Returns the current record's "datesortie" value
 * @method string              getMotif()           Returns the current record's "motif" value
 * @method date                getEtatAcc()         Returns the current record's "etat_acc" value
 * @method date                getEtatMat()         Returns the current record's "etat_mat" value
 * @method Secteur             getSecteur()         Returns the current record's "Pps" value
 * @method Secteur             getPps()             Returns the current record's "Secteur" value
 * @method Orientation         getOrientation()     Returns the current record's "Orientation" value
 * @method Quartier            getQuartier()        Returns the current record's "Quartier" value
 * @method Doctrine_Collection getDgescos()         Returns the current record's "Dgescos" collection
 * @method Doctrine_Collection getEleveAvss()       Returns the current record's "EleveAvss" collection
 * @method Doctrine_Collection getEleves()          Returns the current record's "Eleves" collection
 * @method Doctrine_Collection getMdphs()           Returns the current record's "Mdphs" collection
 * @method Doctrine_Collection getModnonscos()      Returns the current record's "Modnonscos" collection
 * @method Doctrine_Collection getTuteur()          Returns the current record's "Tuteur" collection
 * @method Doctrine_Collection getReunions()        Returns the current record's "Reunions" collection
 * @method Doctrine_Collection getSessadobtenus()   Returns the current record's "Sessadobtenus" collection
 * @method Doctrine_Collection getSuivitExternes()  Returns the current record's "SuivitExternes" collection
 * @method Doctrine_Collection getTransportobtenu() Returns the current record's "Transportobtenu" collection
 * @method Doctrine_Collection getMails()           Returns the current record's "Mails" collection
 * @method Eleve               setQuartierId()      Sets the current record's "quartier_id" value
 * @method Eleve               setSecteurId()       Sets the current record's "secteur_id" value
 * @method Eleve               setPpsId()           Sets the current record's "secteur_id" value
 * @method Eleve               setIne()             Sets the current record's "ine" value
 * @method Eleve               setNumeromdph()      Sets the current record's "numeromdph" value
 * @method Eleve               setNom()             Sets the current record's "nom" value
 * @method Eleve               setPrenom()          Sets the current record's "prenom" value
 * @method Eleve               setDatenaissance()   Sets the current record's "datenaissance" value
 * @method Eleve               setAdresseelevebat() Sets the current record's "adresseelevebat" value
 * @method Eleve               setAdresseleverue()  Sets the current record's "adresseleverue" value
 * @method Eleve               setNotes()           Sets the current record's "notes" value
 * @method Eleve               setSexe()            Sets the current record's "sexe" value
 * @method Eleve               setDatesortie()      Sets the current record's "datesortie" value
 * @method Eleve               setMotif()           Sets the current record's "motif" value
 * @method Eleve               setEtatAcc()         Sets the current record's "etat_acc" value
 * @method Eleve               setEtatMat()         Sets the current record's "etat_mat" value
 * @method Eleve               setSecteur()         Sets the current record's "Secteur" value
 * @method Eleve               setPps()             Sets the current record's "Pps" value
 * @method Eleve               setOrientation()     Sets the current record's "Orientation" value
 * @method Eleve               setQuartier()        Sets the current record's "Quartier" value
 * @method Eleve               setDgescos()         Sets the current record's "Dgescos" collection
 * @method Eleve               setEleveAvss()       Sets the current record's "EleveAvss" collection
 * @method Eleve               setEleves()          Sets the current record's "Eleves" collection
 * @method Eleve               setMdphs()           Sets the current record's "Mdphs" collection
 * @method Eleve               setModnonscos()      Sets the current record's "Modnonscos" collection
 * @method Eleve               setTuteur()          Sets the current record's "Tuteur" collection
 * @method Eleve               setReunions()        Sets the current record's "Reunions" collection
 * @method Eleve               setSessadobtenus()   Sets the current record's "Sessadobtenus" collection
 * @method Eleve               setSuivitExternes()  Sets the current record's "SuivitExternes" collection
 * @method Eleve               setTransportobtenu() Sets the current record's "Transportobtenu" collection
 * @method Eleve               setMails()           Sets the current record's "Mails" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEleve extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eleve');
        $this->hasColumn('quartier_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 8,
             ));
        $this->hasColumn('secteur_id', 'integer', null, array(
             'type' => 'integer',
             ));
		$this->hasColumn('pps_id', 'integer', null, array(
             'type' => 'integer',
			 'notnull' => false,
             ));
        $this->hasColumn('ine', 'string', 11, array(
             'type' => 'string',
             'unique' => true,
             'length' => 11,
             ));
        $this->hasColumn('numeromdph', 'string', 11, array(
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('nom', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'regexp' => '/^([\\s]*[-A-Za-zàáâãäåçèéêëìíîïðòóôõöùúûüýÿ]+[\\s]*)+$/',
             'length' => 100,
             ));
        $this->hasColumn('prenom', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'regexp' => '/^([\\s]*[-A-Za-zàáâãäåçèéêëìíîïðòóôõöùúûüýÿ]+[\\s]*)+$/',
             'length' => 100,
             ));
        $this->hasColumn('datenaissance', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('adresseelevebat', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('adresseleverue', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('sexe', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('datesortie', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('motif', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('etat_acc', 'date', null, array(
             'type' => 'date',
             ));
		$this->hasColumn('etat_mat', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Secteur', array(
             'local' => 'secteur_id',
             'foreign' => 'id'));
			 
	    $this->hasOne('Pps', array(
             'local' => 'pps_id',
             'foreign' => 'id'));

        $this->hasOne('Orientation', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasOne('Quartier', array(
             'local' => 'quartier_id',
             'foreign' => 'id'));

        $this->hasMany('Dgesco as Dgescos', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('EleveAvs as EleveAvss', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('EleveMateriel as Eleves', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('Mdph as Mdphs', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('Modnonsco as Modnonscos', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('Tuteur', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('Reunion as Reunions', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('Sessadobtenu as Sessadobtenus', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('SuivitExterne as SuivitExternes', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('Transportobtenu', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));

        $this->hasMany('Mail as Mails', array(
             'local' => 'id',
             'foreign' => 'eleve_id'));
    }
}
