<?php

/**
 * BaseSessadobtenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eleve_id
 * @property integer $sessad_id
 * @property date $datedebut
 * @property date $datefin
 * @property integer $demandesessad_id
 * @property integer $ordre
 * @property Sessad $Sessad
 * @property Eleve $Eleve
 * @property DemandeSessad $DemandeSessad
 * 
 * @method integer       getEleveId()          Returns the current record's "eleve_id" value
 * @method integer       getSessadId()         Returns the current record's "sessad_id" value
 * @method date          getDatedebut()        Returns the current record's "datedebut" value
 * @method date          getDatefin()          Returns the current record's "datefin" value
 * @method integer       getDemandesessadId()  Returns the current record's "demandesessad_id" value
 * @method integer       getOrdre()            Returns the current record's "ordre" value
 * @method Sessad        getSessad()           Returns the current record's "Sessad" value
 * @method Eleve         getEleve()            Returns the current record's "Eleve" value
 * @method DemandeSessad getDemandeSessad()    Returns the current record's "DemandeSessad" value
 * @method Sessadobtenu  setEleveId()          Sets the current record's "eleve_id" value
 * @method Sessadobtenu  setSessadId()         Sets the current record's "sessad_id" value
 * @method Sessadobtenu  setDatedebut()        Sets the current record's "datedebut" value
 * @method Sessadobtenu  setDatefin()          Sets the current record's "datefin" value
 * @method Sessadobtenu  setDemandesessadId()  Sets the current record's "demandesessad_id" value
 * @method  Sessadobtenu setOrdre()            Sets the current record's "ordre" value
 * @method Sessadobtenu  setSessad()           Sets the current record's "Sessad" value
 * @method Sessadobtenu  setEleve()            Sets the current record's "Eleve" value
 * @method Sessadobtenu  setDemandeSessad()    Sets the current record's "DemandeSessad" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSessadobtenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sessad_obtenu');
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sessad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('datedebut', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('demandesessad_id', 'integer', null, array(
             'type' => 'integer',
             ));
	    $this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sessad', array(
             'local' => 'sessad_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));

        $this->hasOne('DemandeSessad', array(
             'local' => 'demandesessad_id',
             'foreign' => 'id'));
    }
}
