<?php

/**
 * BaseBilan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specialiste_id
 * @property integer $mdph_id
 * @property string $libelle_bilan
 * @property date $date_bilan
 * @property clob $notes
 * @property integer $naturebilan_id
 * @property Specialiste $specialiste
 * @property Mdph $mdph
 * @property Naturebilan $Naturebilan
 * @property Specialiste $Specialiste
 * @property Mdph $Mdph
 * 
 * @method integer     getSpecialisteId()  Returns the current record's "specialiste_id" value
 * @method integer     getMdphId()         Returns the current record's "mdph_id" value
 * @method string      getLibelleBilan()   Returns the current record's "libelle_bilan" value
 * @method date        getDateBilan()      Returns the current record's "date_bilan" value
 * @method clob        getNotes()          Returns the current record's "notes" value
 * @method integer     getNaturebilanId()  Returns the current record's "naturebilan_id" value
 * @method Specialiste getSpecialiste()    Returns the current record's "specialiste" value
 * @method Mdph        getMdph()           Returns the current record's "mdph" value
 * @method Naturebilan getNaturebilan()    Returns the current record's "Naturebilan" value
 * @method Specialiste getSpecialiste()    Returns the current record's "Specialiste" value
 * @method Mdph        getMdph()           Returns the current record's "Mdph" value
 * @method Bilan       setSpecialisteId()  Sets the current record's "specialiste_id" value
 * @method Bilan       setMdphId()         Sets the current record's "mdph_id" value
 * @method Bilan       setLibelleBilan()   Sets the current record's "libelle_bilan" value
 * @method Bilan       setDateBilan()      Sets the current record's "date_bilan" value
 * @method Bilan       setNotes()          Sets the current record's "notes" value
 * @method Bilan       setNaturebilanId()  Sets the current record's "naturebilan_id" value
 * @method Bilan       setSpecialiste()    Sets the current record's "specialiste" value
 * @method Bilan       setMdph()           Sets the current record's "mdph" value
 * @method Bilan       setNaturebilan()    Sets the current record's "Naturebilan" value
 * @method Bilan       setSpecialiste()    Sets the current record's "Specialiste" value
 * @method Bilan       setMdph()           Sets the current record's "Mdph" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBilan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bilan');
        $this->hasColumn('specialiste_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('mdph_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('libelle_bilan', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('date_bilan', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('naturebilan_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Specialiste as specialiste', array(
             'local' => 'specialiste_id',
             'foreign' => 'id'));

        $this->hasOne('Mdph as mdph', array(
             'local' => 'mdph_id',
             'foreign' => 'id'));

        $this->hasOne('Naturebilan', array(
             'local' => 'naturebilan_id',
             'foreign' => 'id'));

        $this->hasOne('Specialiste', array(
             'local' => 'specialiste_id',
             'foreign' => 'id'));

        $this->hasOne('Mdph', array(
             'local' => 'mdph_id',
             'foreign' => 'id'));
    }
}