<?php

/**
 * BaseAnneescolaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $datedebutanneescolaire
 * @property date $datefinanneescolaire
 * @property Doctrine_Collection $Dgescos
 * 
 * @method date                getDatedebutanneescolaire() Returns the current record's "datedebutanneescolaire" value
 * @method date                getDatefinanneescolaire()   Returns the current record's "datefinanneescolaire" value
 * @method Doctrine_Collection getDgescos()                Returns the current record's "Dgescos" collection
 * @method Anneescolaire       setDatedebutanneescolaire() Sets the current record's "datedebutanneescolaire" value
 * @method Anneescolaire       setDatefinanneescolaire()   Sets the current record's "datefinanneescolaire" value
 * @method Anneescolaire       setDgescos()                Sets the current record's "Dgescos" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnneescolaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anneescolaire');
        $this->hasColumn('datedebutanneescolaire', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefinanneescolaire', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dgesco as Dgescos', array(
             'local' => 'id',
             'foreign' => 'anneescolaire_id'));
    }
}