<?php

/**
 * BaseContratAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etabsco_id
 * @property integer $avs_id
 * @property integer $typecontratavs_id
 * @property integer $temps_hebdo
 * @property date $date_debut_contrat
 * @property date $date_fin_contrat
 * @property date $date_fin_projete
 * @property clob $commentaire
 * @property Avs $Avs
 * @property Etabsco $Etabsco
 * @property TypeContratAvs $TypeContratAvs
 * @property Doctrine_Collection $PositionAvss
 * 
 * @method integer             getEtabscoId()          Returns the current record's "etabsco_id" value
 * @method integer             getAvsId()              Returns the current record's "avs_id" value
 * @method integer             getTypecontratavsId()   Returns the current record's "typecontratavs_id" value
 * @method integer             getTempsHebdo()         Returns the current record's "temps_hebdo" value
 * @method date                getDateDebutContrat()   Returns the current record's "date_debut_contrat" value
 * @method date                getDateFinContrat()     Returns the current record's "date_fin_contrat" value
 * @method date                getDateFinProjete()     Returns the current record's "date_fin_projete" value
 * @method clob                getCommentaire()        Returns the current record's "commentaire" value
 * @method Avs                 getAvs()                Returns the current record's "Avs" value
 * @method Etabsco             getEtabsco()            Returns the current record's "Etabsco" value
 * @method TypeContratAvs      getTypeContratAvs()     Returns the current record's "TypeContratAvs" value
 * @method Doctrine_Collection getPositionAvss()       Returns the current record's "PositionAvss" collection
 * @method ContratAvs          setEtabscoId()          Sets the current record's "etabsco_id" value
 * @method ContratAvs          setAvsId()              Sets the current record's "avs_id" value
 * @method ContratAvs          setTypecontratavsId()   Sets the current record's "typecontratavs_id" value
 * @method ContratAvs          setTempsHebdo()         Sets the current record's "temps_hebdo" value
 * @method ContratAvs          setDateDebutContrat()   Sets the current record's "date_debut_contrat" value
 * @method ContratAvs          setDateFinContrat()     Sets the current record's "date_fin_contrat" value
 * @method ContratAvs          setDateFinProjete()     Sets the current record's "date_fin_projete" value
 * @method EleveAvs            setCommentaire()        Sets the current record's "commentaire" value
 * @method ContratAvs          setAvs()                Sets the current record's "Avs" value
 * @method ContratAvs          setEtabsco()            Sets the current record's "Etabsco" value
 * @method ContratAvs          setTypeContratAvs()     Sets the current record's "TypeContratAvs" value
 * @method ContratAvs          setPositionAvss()       Sets the current record's "PositionAvss" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContratAvs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contrat_avs');
        $this->hasColumn('etabsco_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('avs_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('typecontratavs_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('temps_hebdo', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('date_debut_contrat', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_fin_contrat', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_fin_projete', 'date', null, array(
             'type' => 'date',
             ));
		$this->hasColumn('commentaire', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Avs', array(
             'local' => 'avs_id',
             'foreign' => 'id'));

        $this->hasOne('Etabsco', array(
             'local' => 'etabsco_id',
             'foreign' => 'id'));

        $this->hasOne('TypeContratAvs', array(
             'local' => 'typecontratavs_id',
             'foreign' => 'id'));

        $this->hasMany('PositionAvs as PositionAvss', array(
             'local' => 'id',
             'foreign' => 'contratavs_id'));
    }
}