<?php

/**
 * BaseNiveauscolairespe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $NiveauScolaire
 * @property string $LibelleNiveauScolaire
 * @property Doctrine_Collection $Modnonscos
 * 
 * @method string              getNiveauScolaire()      Returns the current record's "NiveauScolaire" value
 * @method string              getLibelleNiveauScolaire()  Returns the current record's "LibelleNiveauScolaire" value
 * @method Doctrine_Collection getModnonscos()           Returns the current record's "Modnonscos" collection
 * @method Niveauscolaire      setNiveauScolaire()      Sets the current record's "NiveauScolaire" value
 * @method Niveauscolaire      setLibelleNiveauScolaire()  Sets the current record's "LibelleNiveauScolaire" value
 * @method Niveauscolaire      setModnonscos()           Sets the current record's "Modnonscos" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNiveauscolairespe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('niveauscolairespe');
        $this->hasColumn('NiveauScolaire', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('LibelleNiveauScolaire', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Modnonsco as Modnonscos', array(
             'local' => 'id',
             'foreign' => 'niveauscolairespe_id'));
    }
}