<?php

/**
 * BasePps
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libellepps
 * @property Doctrine_Collection $Reunions
 * 
 * @method string              getLibellepps() Returns the current record's "libellepps" value
 * @method Doctrine_Collection getEleves()           Returns the current record's "Eleves" collection
 * @method Pps                  setLibellepps() Sets the current record's "libellepps" value
 * @method Pps                  setEleves()    Sets the current record's "Eleves" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePps extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pps');
        $this->hasColumn('libellepps', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Eleve as Eleves', array(
             'local' => 'id',
             'foreign' => 'pps_id'));
    }
}