<?php

/**
 * BaseTuteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eleve_id
 * @property integer $responsableeleve_id
 * @property boolean $tuteurlegal
 * @property integer $typeresponsableeleve_id
 * @property string $autretyperesponsable
 * @property Eleve $Eleve
 * @property ResponsableEleve $ResponsableEleve
 * @property TypeResponsableEleve $TypeResponsableEleve
 * 
 * @method integer              getEleveId()                 Returns the current record's "eleve_id" value
 * @method integer              getResponsableeleveId()      Returns the current record's "responsableeleve_id" value
 * @method boolean              getTuteurlegal()             Returns the current record's "tuteurlegal" value
 * @method integer              getTyperesponsableeleveId()  Returns the current record's "typeresponsableeleve_id" value
 * @method string               getAutretyperesponsable()    Returns the current record's "autretyperesponsable" value
 * @method Eleve                getEleve()                   Returns the current record's "Eleve" value
 * @method ResponsableEleve     getResponsableEleve()        Returns the current record's "ResponsableEleve" value
 * @method TypeResponsableEleve getTypeResponsableEleve()    Returns the current record's "TypeResponsableEleve" value
 * @method Tuteur               setEleveId()                 Sets the current record's "eleve_id" value
 * @method Tuteur               setResponsableeleveId()      Sets the current record's "responsableeleve_id" value
 * @method Tuteur               setTuteurlegal()             Sets the current record's "tuteurlegal" value
 * @method Tuteur               setTyperesponsableeleveId()  Sets the current record's "typeresponsableeleve_id" value
 * @method Tuteur               setAutretyperesponsable()    Sets the current record's "autretyperesponsable" value
 * @method Tuteur               setEleve()                   Sets the current record's "Eleve" value
 * @method Tuteur               setResponsableEleve()        Sets the current record's "ResponsableEleve" value
 * @method Tuteur               setTypeResponsableEleve()    Sets the current record's "TypeResponsableEleve" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTuteur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tuteur');
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('responsableeleve_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tuteurlegal', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('typeresponsableeleve_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
		$this->hasColumn('autretyperesponsable', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => 50,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));

        $this->hasOne('ResponsableEleve', array(
             'local' => 'responsableeleve_id',
             'foreign' => 'id'));

        $this->hasOne('TypeResponsableEleve', array(
             'local' => 'typeresponsableeleve_id',
             'foreign' => 'id'));
    }
}