<?php

/**
 * BaseDemandeAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mdph_id
 * @property integer $conditionsuspensive_id
 * @property integer $naturecontratavs_id
 * @property date $date_demande_avs
 * @property integer $quotitehorrairenotifie
 * @property date $datedebutnotif
 * @property date $datefinnotif
 * @property date $datedecisioncda
 * @property boolean $decisioncda
 * @property boolean $traite
 * @property boolean $etat
 * @property clob $notes
 * @property date $dateRecepDemandERF
 * @property date $dateDemandDSM
 * @property date $dateDeciDSM
 * @property date $datetransDeciERF
 * @property Mdph $Mdph
 * @property Naturecontratavs $Naturecontratavs
 * @property Conditionsuspensive $Conditionsuspensive
 * 
 * @method integer             getMdphId()                 Returns the current record's "mdph_id" value
 * @method integer             getConditionsuspensiveId()  Returns the current record's "conditionsuspensive_id" value
 * @method integer             getNaturecontratavsId()     Returns the current record's "naturecontratavs_id" value
 * @method date                getDateDemandeAvs()         Returns the current record's "date_demande_avs" value
 * @method integer             getQuotitehorrairenotifie() Returns the current record's "quotitehorrairenotifie" value
 * @method date                getDatedebutnotif()         Returns the current record's "datedebutnotif" value
 * @method date                getDatefinnotif()           Returns the current record's "datefinnotif" value
 * @method date                getDatedecisioncda()        Returns the current record's "datedecisioncda" value
 * @method boolean             getDecisioncda()            Returns the current record's "decisioncda" value
 * @method boolean             getTraite()                 Returns the current record's "traite" value
 * @method boolean             getEtat()                   Returns the current record's "etat" value
 * @method clob                getNotes()                  Returns the current record's "notes" value
 * @method date                getDateRecepDemandERF()     Returns the current record's "dateRecepDemandERF" value
 * @method date                getDateDemandDSM()          Returns the current record's "dateDemandDSM" value
 * @method date                getDateDeciDSM()            Returns the current record's "dateDeciDSM" value
 * @method date                getDatetransDeciERF()       Returns the current record's "datetransDeciERF" value
 * @method Mdph                getMdph()                   Returns the current record's "Mdph" value
 * @method Naturecontratavs    getNaturecontratavs()       Returns the current record's "Naturecontratavs" value
 * @method Conditionsuspensive getConditionsuspensive()    Returns the current record's "Conditionsuspensive" value
 * @method DemandeAvs          setMdphId()                 Sets the current record's "mdph_id" value
 * @method DemandeAvs          setConditionsuspensiveId()  Sets the current record's "conditionsuspensive_id" value
 * @method DemandeAvs          setNaturecontratavsId()     Sets the current record's "naturecontratavs_id" value
 * @method DemandeAvs          setDateDemandeAvs()         Sets the current record's "date_demande_avs" value
 * @method DemandeAvs          setQuotitehorrairenotifie() Sets the current record's "quotitehorrairenotifie" value
 * @method DemandeAvs          setDatedebutnotif()         Sets the current record's "datedebutnotif" value
 * @method DemandeAvs          setDatefinnotif()           Sets the current record's "datefinnotif" value
 * @method DemandeAvs          setDatedecisioncda()        Sets the current record's "datedecisioncda" value
 * @method DemandeAvs          setDecisioncda()            Sets the current record's "decisioncda" value
 * @method DemandeAvs          setTraite()                 Sets the current record's "traite" value
 * @method DemandeAvs          setEtat()                   Sets the current record's "etat" value
 * @method DemandeAvs          setNotes()                  Sets the current record's "notes" value
 * @method DemandeAvs          setDateRecepDemandERF()     Sets the current record's "dateRecepDemandERF" value
 * @method DemandeAvs          setDateDemandDSM()          Sets the current record's "dateDemandDSM" value
 * @method DemandeAvs          setDateDeciDSM()            Sets the current record's "dateDeciDSM" value
 * @method DemandeAvs          setDatetransDeciERF()       Sets the current record's "datetransDeciERF" value
 * @method DemandeAvs          setMdph()                   Sets the current record's "Mdph" value
 * @method DemandeAvs          setNaturecontratavs()       Sets the current record's "Naturecontratavs" value
 * @method DemandeAvs          setConditionsuspensive()    Sets the current record's "Conditionsuspensive" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDemandeAvs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('demande_avs');
        $this->hasColumn('mdph_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('conditionsuspensive_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('naturecontratavs_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date_demande_avs', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('quotitehorrairenotifie', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('datedebutnotif', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefinnotif', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datedecisioncda', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('decisioncda', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('traite', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('etat', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('dateRecepDemandERF', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dateDemandDSM', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dateDeciDSM', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datetransDeciERF', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mdph', array(
             'local' => 'mdph_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasOne('Naturecontratavs', array(
             'local' => 'naturecontratavs_id',
             'foreign' => 'id'));

        $this->hasOne('Conditionsuspensive', array(
             'local' => 'conditionsuspensive_id',
             'foreign' => 'id'));
    }
}