<?php

/**
 * BasePiecesDossier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mdph_id
 * @property string $libellepiece
 * @property boolean $restitue
 * @property Mdph $Mdph
 * @property date $daterecep
 * 
 * @method integer       getMdphId()       Returns the current record's "mdph_id" value
 * @method string        getLibellepiece() Returns the current record's "libellepiece" value
 * @method boolean       getRestitue()     Returns the current record's "restitue" value
 * @method Mdph          getMdph()         Returns the current record's "Mdph" value
 * @method date          getDaterecep()    Returns the current record's "daterecep" value
 * @method PiecesDossier setMdphId()       Sets the current record's "mdph_id" value
 * @method PiecesDossier setLibellepiece() Sets the current record's "libellepiece" value
 * @method PiecesDossier setRestitue()     Sets the current record's "restitue" value
 * @method PiecesDossier setMdph()         Sets the current record's "Mdph" value
 * @method PiecesDossier setDaterecep()    Sets the current record's "daterecep" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePiecesDossier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pieces_dossier');
        $this->hasColumn('mdph_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('libellepiece', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('restitue', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('daterecep', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mdph', array(
             'local' => 'mdph_id',
             'foreign' => 'id'));
    }
}