<?php

/**
 * BaseTypePositionAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelletypepositionavs
 * @property Doctrine_Collection $PositionsAvss
 * 
 * @method string              getLibelletypepositionavs() Returns the current record's "libelletypepositionavs" value
 * @method Doctrine_Collection getPositionsAvss()          Returns the current record's "PositionsAvss" collection
 * @method TypePositionAvs     setLibelletypepositionavs() Sets the current record's "libelletypepositionavs" value
 * @method TypePositionAvs     setPositionsAvss()          Sets the current record's "PositionsAvss" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypePositionAvs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_position_avs');
        $this->hasColumn('libelletypepositionavs', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PositionAvs as PositionsAvss', array(
             'local' => 'id',
             'foreign' => 'typepositionavs_id'));
    }
}