<?php

/**
 * BaseEleveMateriel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eleve_id
 * @property integer $materiel_id
 * @property date $dateconvention
 * @property date $datedebut
 * @property date $datefin
 * @property date $dateremiseerf
 * @property date $dateremiseparent
 * @property date $autorisationparent
 * @property Materiel $Materiel
 * @property Eleve $Eleve
 * @property string $numero_convention
 * @property string $chemin_conv
 * 
 * @method integer       getEleveId()        Returns the current record's "eleve_id" value
 * @method integer       getMaterielId()     Returns the current record's "materiel_id" value
 * @method date          getDateconvention() Returns the current record's "dateconvention" value
 * @method date          getDatedebut()      Returns the current record's "datedebut" value
 * @method date          getDatefin()        Returns the current record's "datefin" value
 * @method date          getRemiseERF()      Returns the current record's "dateremiseerf" value
 * @method date          getDateRemiseErf()  Returns the current record's "dateremiseerf" value
 * @method date          getDateRemiseParent()  Returns the current record's "dateremiseparent" value
 * @method date          getAutorisationParent()  Returns the current record's "autorisationparent" value
 * @method Materiel      getMateriel()       Returns the current record's "Materiel" value
 * @method Eleve         getEleve()          Returns the current record's "Eleve" value
 * @method string        getNumeroConvention()  Returns the current record's "numero_convention" value
 * @method string        getCheminConv()  Returns the current record's "chemin_conv" value
 * @method EleveMateriel setEleveId()        Sets the current record's "eleve_id" value
 * @method EleveMateriel setMaterielId()     Sets the current record's "materiel_id" value
 * @method EleveMateriel setDateconvention() Sets the current record's "dateconvention" value
 * @method EleveMateriel setDatedebut()      Sets the current record's "datedebut" value
 * @method EleveMateriel setDatefin()        Sets the current record's "datefin" value
 * @method EleveMateriel setDateRemiseErf()    Sets the current record's "dateremiseerf" value
 * @method EleveMateriel setDateRemiseParent()  Sets the current record's "dateremiseparent" value
 * @method EleveMateriel setAutorisationParent()  Sets the current record's "autorisationparent" value
 * @method EleveMateriel setMateriel()       Sets the current record's "Materiel" value
 * @method EleveMateriel setEleve()          Sets the current record's "Eleve" value
 * @method EleveMateriel setNumeroConvention() Sets the current record's "numero_convention" value
 * @method EleveMateriel setCheminConv() Sets the current record's "chemin_conv" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEleveMateriel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eleve_materiel');
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             ));
        $this->hasColumn('materiel_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             ));
        $this->hasColumn('dateconvention', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datedebut', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             ));
		$this->hasColumn('dateremiseerf', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dateremiseparent', 'date', null, array(
             'type' => 'date',
             ));
	    $this->hasColumn('autorisationparent', 'date', null, array(
             'type' => 'date',
             ));	 
		$this->hasColumn('numero_convention', 'string', 11, array(
             'type' => 'string',
             'unique' => false,
             'length' => 11,
             ));
		$this->hasColumn('chemin_conv', 'string', 150, array(
             'type' => 'string',
             'unique' => false,
             'length' => 11,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Materiel', array(
             'local' => 'materiel_id',
             'foreign' => 'id'));

        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));
    }
}