<?php

/**
 * BaseMail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eleve_id
 * @property integer $sfGuardUser_id
 * @property date $date
 * @property string $sujet
 * @property clob $texte
 * @property Eleve $Eleve
 * 
 * @method integer getEleveId()        Returns the current record's "eleve_id" value
 * @method integer getSfGuardUserId()  Returns the current record's "sfGuardUser_id" value
 * @method date    getDate()           Returns the current record's "date" value
 * @method string  getSujet()          Returns the current record's "sujet" value
 * @method clob    getTexte()          Returns the current record's "texte" value
 * @method Eleve   getEleve()          Returns the current record's "Eleve" value
 * @method Mail    setEleveId()        Sets the current record's "eleve_id" value
 * @method Mail    setSfGuardUserId()  Sets the current record's "sfGuardUser_id" value
 * @method Mail    setDate()           Sets the current record's "date" value
 * @method Mail    setSujet()          Sets the current record's "sujet" value
 * @method Mail    setTexte()          Sets the current record's "texte" value
 * @method Mail    setEleve()          Sets the current record's "Eleve" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mail');
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sfGuardUser_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('sujet', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('texte', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));
		$this->hasOne('sfGuardUser as sfguarduser', array(
             'local' => 'sfguarduser_id',
             'foreign' => 'id'));
    }
}