<?php

/**
 * BaseNaturecontratavs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $naturecontrat
 * @property string $nouvnomnaturecontrat
 * @property Doctrine_Collection $DemandeAvss
 * 
 * @method string              getNaturecontrat()        Returns the current record's "naturecontrat" value
 * @method string              getNouvnomnaturecontrat() Returns the current record's "nouvnomnaturecontrat" value
 * @method Doctrine_Collection getDemandeAvss()          Returns the current record's "DemandeAvss" collection
 * @method Naturecontratavs    setNaturecontrat()        Sets the current record's "naturecontrat" value
 * @method Naturecontratavs    setNouvnomnaturecontrat() Sets the current record's "nouvnomnaturecontrat" value
 * @method Naturecontratavs    setDemandeAvss()          Sets the current record's "DemandeAvss" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNaturecontratavs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('naturecontratavs');
        $this->hasColumn('naturecontrat', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nouvnomnaturecontrat', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeAvs as DemandeAvss', array(
             'local' => 'id',
             'foreign' => 'naturecontratavs_id'));
    }
}