<?php

/**
 * BaseMateriel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $marque_id
 * @property integer $typemateriel_id
 * @property integer $catmateriel_id
 * @property string $libellemateriel
 * @property integer $prixachat
 * @property integer $fournisseur_id
 * @property clob $caracteristiquemateriel
 * @property string $numeromateriel
 * @property clob $commentaire
 * @property Typemateriel $Typemateriel
 * @property Catmateriel $Catmateriel
 * @property Marque $Marque
 * @property Fournisseur $Fournisseur
 * @property date $dateachat
 * @property Doctrine_Collection $EleveMateriel
 * @property Doctrine_Collection $MouvementMateriels
 * 
 * @method integer             getMarqueId()                Returns the current record's "marque_id" value
 * @method integer             getTypematerielId()          Returns the current record's "typemateriel_id" value
 * @method integer             getCatmaterielId()           Returns the current record's "catmateriel_id" value
 * @method string              getLibellemateriel()         Returns the current record's "libellemateriel" value
 * @method integer             getPrixachat()               Returns the current record's "prixachat" value
 * @method integer             getFournisseurId()           Returns the current record's "fournisseur_id" value
 * @method clob                getCaracteristiquemateriel() Returns the current record's "caracteristiquemateriel" value
 * @method string              getNumeromateriel()          Returns the current record's "numeromateriel" value
 * @method clob                getCommentaire()             Returns the current record's "commentaire" value
 * @method Typemateriel        getTypemateriel()            Returns the current record's "Typemateriel" value
 * @method Catmateriel         getCatmateriel()             Returns the current record's "Catmateriel" value
 * @method Marque              getMarque()                  Returns the current record's "Marque" value
 * @method Fournisseur         getFournisseur()             Returns the current record's "Fournisseur" value
 * @method date                getDateachat()               Returns the current record's "dateachat" value
 * @method Doctrine_Collection getEleveMateriel()           Returns the current record's "EleveMateriel" collection
 * @method Doctrine_Collection getMouvementMateriels()      Returns the current record's "MouvementMateriels" collection
 * @method Materiel            setMarqueId()                Sets the current record's "marque_id" value
 * @method Materiel            setTypematerielId()          Sets the current record's "typemateriel_id" value
 * @method Materiel            setCatmaterielId()           Sets the current record's "catmateriel_id" value
 * @method Materiel            setLibellemateriel()         Sets the current record's "libellemateriel" value
 * @method Materiel            setPrixachat()               Sets the current record's "prixachat" value
 * @method Materiel            setFournisseurId()           Sets the current record's "fournisseur_id" value
 * @method Materiel            setCaracteristiquemateriel() Sets the current record's "caracteristiquemateriel" value
 * @method Materiel            setNumeromateriel()          Sets the current record's "numeromateriel" value
 * @method Materiel            setCommentaire()             Sets the current record's "commentaire" value
 * @method Materiel            setTypemateriel()            Sets the current record's "Typemateriel" value
 * @method Materiel            setCatmateriel()             Sets the current record's "Catmateriel" value
 * @method Materiel            setMarque()                  Sets the current record's "Marque" value
 * @method Materiel            setFournisseur()             Sets the current record's "Fournisseur" value
 * @method Materiel            setDateachat()               Sets the current record's "dateachat" value
 * @method Materiel            setEleveMateriel()           Sets the current record's "EleveMateriel" collection
 * @method Materiel            setMouvementMateriels()      Sets the current record's "MouvementMateriels" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMateriel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materiel');
        $this->hasColumn('marque_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('typemateriel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('catmateriel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('libellemateriel', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('prixachat', 'integer', null, array(
             'type' => 'decimal',
			 'scale' => 2,
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('fournisseur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
		$this->hasColumn('dateachat', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('caracteristiquemateriel', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('numeromateriel', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('commentaire', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Typemateriel', array(
             'local' => 'typemateriel_id',
             'foreign' => 'id'));

        $this->hasOne('Catmateriel', array(
             'local' => 'catmateriel_id',
             'foreign' => 'id'));

        $this->hasOne('Marque', array(
             'local' => 'marque_id',
             'foreign' => 'id'));

        $this->hasOne('Fournisseur', array(
             'local' => 'fournisseur_id',
             'foreign' => 'id'));

        $this->hasMany('EleveMateriel', array(
             'local' => 'id',
             'foreign' => 'materiel_id'));

        $this->hasMany('MouvementMateriel as MouvementMateriel', array(
             'local' => 'id',
             'foreign' => 'materiel_id'));
    }
}