<?php

/**
 * BaseResponsableEleve
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Tuteur
 * 
 * @method Doctrine_Collection getTuteur() Returns the current record's "Tuteur" collection
 * @method ResponsableEleve    setTuteur() Sets the current record's "Tuteur" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResponsableEleve extends Personne
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('responsable_eleve');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tuteur', array(
             'local' => 'id',
             'foreign' => 'responsableeleve_id'));
    }
}