<?php

/**
 * BaseTypesessad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelletypesessad
 * @property Doctrine_Collection $DemandeSessads
 * @property Doctrine_Collection $Sessads
 * 
 * @method string              getLibelletypesessad() Returns the current record's "libelletypesessad" value
 * @method Doctrine_Collection getDemandeSessads()    Returns the current record's "DemandeSessads" collection
 * @method Doctrine_Collection getSessads()           Returns the current record's "Sessads" collection
 * @method Typesessad          setLibelletypesessad() Sets the current record's "libelletypesessad" value
 * @method Typesessad          setDemandeSessads()    Sets the current record's "DemandeSessads" collection
 * @method Typesessad          setSessads()           Sets the current record's "Sessads" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypesessad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typesessad');
        $this->hasColumn('libelletypesessad', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeSessad as DemandeSessads', array(
             'local' => 'id',
             'foreign' => 'typesessad_id'));

        $this->hasMany('Sessad as Sessads', array(
             'local' => 'id',
             'foreign' => 'typesessad_id'));
    }
}