<?php

/**
 * BaseTypeetablissementnonsco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nomtypeetablissement
 * @property Doctrine_Collection $Etabnonscos
 * 
 * @method string              getNomtypeetablissement() Returns the current record's "nomtypeetablissement" value
 * @method Doctrine_Collection getEtabnonscos()             Returns the current record's "Etabnonscos" collection
 * @method Typeetablissementnonsco   setNomtypeetablissement() Sets the current record's "nomtypeetablissement" value
 * @method Typeetablissementnonsco   setEtabnonscos()             Sets the current record's "Etabnonscos" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeetablissementnonsco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typeetablissementnonsco');
        $this->hasColumn('nomtypeetablissement', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Etabnonsco as Etabnonscos', array(
             'local' => 'id',
             'foreign' => 'typeetablissement_id'));


    }
}