<?php

/**
 * BaseTypematdemande
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelletypemateriel
 * @property Doctrine_Collection $DemandeMateriels
 * 
 * @method string              getLibelletypemateriel() Returns the current record's "libelletypemateriel" value
 * @method Doctrine_Collection getDemandeMateriels()    Returns the current record's "DemandeMateriels" collection
 * @method Typematdemande      setLibelletypemateriel() Sets the current record's "libelletypemateriel" value
 * @method Typematdemande      setDemandeMateriels()    Sets the current record's "DemandeMateriels" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypematdemande extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typematdemande');
        $this->hasColumn('libelletypemateriel', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeMateriel as DemandeMateriels', array(
             'local' => 'id',
             'foreign' => 'typematdemande_id'));
    }
}