<?php

/**
 * BaseClassespe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelle_classe_spe
 * @property Doctrine_Collection $DemandeOrientations
 * @property Doctrine_Collection $Modnonscos
 * 
 * @method string              getLibelleClasseSpe()    Returns the current record's "libelle_classe_spe" value
 * @method Doctrine_Collection getDemandeOrientations() Returns the current record's "DemandeOrientations" collection
 * @method Doctrine_Collection getModnonscos()          Returns the current record's "Modnonscos" collection
 * @method Classespe           setLibelleClasseSpe()    Sets the current record's "libelle_classe_spe" value
 * @method Classespe           setDemandeOrientations() Sets the current record's "DemandeOrientations" collection
 * @method Classespe           setModnonscos()          Sets the current record's "Modnonscos" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassespe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('classespe');
        $this->hasColumn('libelle_classe_spe', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeOrientation as DemandeOrientations', array(
             'local' => 'id',
             'foreign' => 'classespe_id'));

        $this->hasMany('Modnonsco as Modnonscos', array(
             'local' => 'id',
             'foreign' => 'classespe_id'));
    }
}