<?php

/**
 * BaseDemandeTransport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $transport_id
 * @property integer $mdph_id
 * @property date $date_demande_transport
 * @property date $datedebutnotif
 * @property date $datefinnotif
 * @property date $datedecisioncda
 * @property boolean $decisioncda
 * @property boolean $traite
 * @property boolean $etat
 * @property Mdph $Mdph
 * @property Transport $Transport
 * 
 * @method integer          getTransportId()            Returns the current record's "transport_id" value
 * @method integer          getMdphId()                 Returns the current record's "mdph_id" value
 * @method date             getDateDemandeTransport()   Returns the current record's "date_demande_transport" value
 * @method date             getDatedebutnotif()         Returns the current record's "datedebutnotif" value
 * @method date             getDatefinnotif()           Returns the current record's "datefinnotif" value
 * @method date             getDatedecisioncda()        Returns the current record's "datedecisioncda" value
 * @method boolean          getDecisioncda()            Returns the current record's "decisioncda" value
 * @method boolean          getTraite()                 Returns the current record's "traite" value
 * @method boolean          getEtat()                   Returns the current record's "etat" value
 * @method Mdph             getMdph()                   Returns the current record's "Mdph" value
 * @method Transport        getTransport()              Returns the current record's "Transport" value
 * @method DemandeTransport setTransportId()            Sets the current record's "transport_id" value
 * @method DemandeTransport setMdphId()                 Sets the current record's "mdph_id" value
 * @method DemandeTransport setDateDemandeTransport()   Sets the current record's "date_demande_transport" value
 * @method DemandeTransport setDatedebutnotif()         Sets the current record's "datedebutnotif" value
 * @method DemandeTransport setDatefinnotif()           Sets the current record's "datefinnotif" value
 * @method DemandeTransport setDatedecisioncda()        Sets the current record's "datedecisioncda" value
 * @method DemandeTransport setDecisioncda()            Sets the current record's "decisioncda" value
 * @method DemandeTransport setTraite()                 Sets the current record's "traite" value
 * @method DemandeTransport setEtat()                   Sets the current record's "etat" value
 * @method DemandeTransport setMdph()                   Sets the current record's "Mdph" value
 * @method DemandeTransport setTransport()              Sets the current record's "Transport" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDemandeTransport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('demande_transport');
        $this->hasColumn('transport_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mdph_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('date_demande_transport', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datedebutnotif', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefinnotif', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datedecisioncda', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('decisioncda', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('traite', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('etat', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mdph', array(
             'local' => 'mdph_id',
             'foreign' => 'id'));

        $this->hasOne('Transport', array(
             'local' => 'transport_id',
             'foreign' => 'id'));
    }
}