<?php

/**
 * BaseTypeetablissement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nomtypeetablissement
 * @property Doctrine_Collection $Etabscos
 * @property Doctrine_Collection $Classes
 * 
 * @method string              getNomtypeetablissement() Returns the current record's "nomtypeetablissement" value
 * @method Doctrine_Collection getEtabscos()             Returns the current record's "Etabscos" collection
 * @method Doctrine_Collection getClasses()              Returns the current record's "Classes" collection
 * @method Typeetablissement   setNomtypeetablissement() Sets the current record's "nomtypeetablissement" value
 * @method Typeetablissement   setEtabscos()             Sets the current record's "Etabscos" collection
 * @method Typeetablissement   setClasses()              Sets the current record's "Classes" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeetablissement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typeetablissement');
        $this->hasColumn('nomtypeetablissement', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Etabsco as Etabscos', array(
             'local' => 'id',
             'foreign' => 'typeetablissement_id'));

        $this->hasMany('Classe as Classes', array(
             'local' => 'id',
             'foreign' => 'typeetablissement_id'));
    }
}