<?php

/**
 * BaseEnseignant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Orientations
 * 
 * @method Doctrine_Collection getOrientations() Returns the current record's "Orientations" collection
 * @method Enseignant          setOrientations() Sets the current record's "Orientations" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnseignant extends Personne
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('enseignant');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Orientation as Orientations', array(
             'local' => 'id',
             'foreign' => 'enseignant_id'));
    }
}