<?php

/**
 * BaseMouvementMateriel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $materiel_id
 * @property integer $mouvement_id
 * @property date $datedebut
 * @property date $datefin
 * @property Materiel $materiel
 * @property Mouvement $mouvement
 * @property Materiel $Materiel
 * @property Mouvement $Mouvement
 * @property clob $notes
 * 
 * @method integer           getMaterielId()   Returns the current record's "materiel_id" value
 * @method integer           getMouvementId()  Returns the current record's "mouvement_id" value
 * @method date              getDatedebut()    Returns the current record's "datedebut" value
 * @method date              getDatefin()      Returns the current record's "datefin" value
 * @method Materiel          getMateriel()     Returns the current record's "materiel" value
 * @method Mouvement         getMouvement()    Returns the current record's "mouvement" value
 * @method Materiel          getMateriel()     Returns the current record's "Materiel" value
 * @method Mouvement         getMouvement()    Returns the current record's "Mouvement" value
 * @method clob              getNotes()           Returns the current record's "notes" value
 * @method MouvementMateriel setMaterielId()   Sets the current record's "materiel_id" value
 * @method MouvementMateriel setMouvementId()  Sets the current record's "mouvement_id" value
 * @method MouvementMateriel setDatedebut()    Sets the current record's "datedebut" value
 * @method MouvementMateriel setDatefin()      Sets the current record's "datefin" value
 * @method MouvementMateriel setMateriel()     Sets the current record's "materiel" value
 * @method MouvementMateriel setMouvement()    Sets the current record's "mouvement" value
 * @method MouvementMateriel setMateriel()     Sets the current record's "Materiel" value
 * @method MouvementMateriel setMouvement()    Sets the current record's "Mouvement" value
 * @method Eleve             setNotes()        Sets the current record's "notes" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMouvementMateriel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mouvement_materiel');
        $this->hasColumn('materiel_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('mouvement_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('datedebut', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             ));
	    $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Materiel as materiel', array(
             'local' => 'materiel_id',
             'foreign' => 'id'));

        $this->hasOne('Mouvement as mouvement', array(
             'local' => 'mouvement_id',
             'foreign' => 'id'));

        $this->hasOne('Materiel', array(
             'local' => 'materiel_id',
             'foreign' => 'id'));

        $this->hasOne('Mouvement', array(
             'local' => 'mouvement_id',
             'foreign' => 'id'));
    }
}