<?php

/**
 * BaseDemijournee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelledemijournee
 * @property Doctrine_Collection $DemandeOrientations
 * @property Doctrine_Collection $Modnonscos
 * @property Doctrine_Collection $Orientations
 * 
 * @method string              getLibelledemijournee()  Returns the current record's "libelledemijournee" value
 * @method Doctrine_Collection getDemandeOrientations() Returns the current record's "DemandeOrientations" collection
 * @method Doctrine_Collection getModnonscos()          Returns the current record's "Modnonscos" collection
 * @method Doctrine_Collection getOrientations()        Returns the current record's "Orientations" collection
 * @method Demijournee         setLibelledemijournee()  Sets the current record's "libelledemijournee" value
 * @method Demijournee         setDemandeOrientations() Sets the current record's "DemandeOrientations" collection
 * @method Demijournee         setModnonscos()          Sets the current record's "Modnonscos" collection
 * @method Demijournee         setOrientations()        Sets the current record's "Orientations" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDemijournee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('demijournee');
        $this->hasColumn('libelledemijournee', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeOrientation as DemandeOrientations', array(
             'local' => 'id',
             'foreign' => 'demijournee_id'));

        $this->hasMany('Modnonsco as Modnonscos', array(
             'local' => 'id',
             'foreign' => 'demijournee_id'));

        $this->hasMany('Orientation as Orientations', array(
             'local' => 'id',
             'foreign' => 'demijournee_id'));
    }
}