<?php

/**
 * BaseQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $question
 * @property string $num_question
 * @property Reponse $Reponses
 * 
 * @method string   getQuestion() Returns the current record's "question" value
 * @method string   getNumQuestion() Returns the current record's "num_question" value
 * @method Reponse  getReponses() Returns the current record's "Reponses" value
 * @method Question setQuestion() Sets the current record's "question" value
 * @method Question setNumQuestion() Sets the current record's "num_question" value
 * @method Question setReponses() Sets the current record's "Reponses" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question');
		     $this->hasColumn('question', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('num_question', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reponse as Reponses', array(
             'local' => 'id',
             'foreign' => 'question_id'));
    }
}