<?php

/**
 * BaseSessad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etabnonsco_id
 * @property integer $typesessad_id
 * @property integer $ordre
 * @property Etabnonsco $Etabnonsco
 * @property Typesessad $Typesessad
 * @property Doctrine_Collection $Sessadobtenus
 * 
 * @method integer             getEtabnonscoId()  Returns the current record's "etabnonsco_id" value
 * @method integer             getTypesessadId()  Returns the current record's "typesessad_id" value
 * @method Etabnonsco          getEtabnonsco()    Returns the current record's "Etabnonsco" value
 * @method Typesessad          getTypesessad()    Returns the current record's "Typesessad" value
 * @method Doctrine_Collection getSessadobtenus() Returns the current record's "Sessadobtenus" collection
 * @method Sessad              setEtabnonscoId()  Sets the current record's "etabnonsco_id" value
 * @method Sessad              setTypesessadId()  Sets the current record's "typesessad_id" value
 * @method Sessad              setOrdre()        Sets the current record's "ordre" value
 * @method Sessad              setEtabnonsco()    Sets the current record's "Etabnonsco" value
 * @method Sessad              setTypesessad()    Sets the current record's "Typesessad" value
 * @method Sessad              setSessadobtenus() Sets the current record's "Sessadobtenus" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSessad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sessad');
        $this->hasColumn('etabnonsco_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('typesessad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
	    $this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Etabnonsco', array(
             'local' => 'etabnonsco_id',
             'foreign' => 'id',
             'owningSide' => true));

        $this->hasOne('Typesessad', array(
             'local' => 'typesessad_id',
             'foreign' => 'id'));

        $this->hasMany('Sessadobtenu as Sessadobtenus', array(
             'local' => 'id',
             'foreign' => 'sessad_id'));
    }
}