<?php

/**
 * BaseMarque
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libellemarque
 * @property Doctrine_Collection $Materiels
 * 
 * @method string              getLibellemarque() Returns the current record's "libellemarque" value
 * @method Doctrine_Collection getMateriels()     Returns the current record's "Materiels" collection
 * @method Marque              setLibellemarque() Sets the current record's "libellemarque" value
 * @method Marque              setMateriels()     Sets the current record's "Materiels" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarque extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marque');
        $this->hasColumn('libellemarque', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Materiel as Materiels', array(
             'local' => 'id',
             'foreign' => 'marque_id'));
    }
}