<?php

/**
 * BaseNiveauDgesco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nomniveaudegsco
 * @property string $nomLongNiveauDgesco
 * @property Doctrine_Collection $Orientations
 * 
 * @method string              getNomniveaudegsco()     Returns the current record's "nomniveaudegsco" value
 * @method string              getNomLongNiveauDgesco() Returns the current record's "nomLongNiveauDgesco" value
 * @method Doctrine_Collection getOrientations()        Returns the current record's "Orientations" collection
 * @method NiveauDgesco        setNomniveaudegsco()     Sets the current record's "nomniveaudegsco" value
 * @method NiveauDgesco        setNomLongNiveauDgesco() Sets the current record's "nomLongNiveauDgesco" value
 * @method NiveauDgesco        setOrientations()        Sets the current record's "Orientations" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNiveauDgesco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('niveau_dgesco');
        $this->hasColumn('nomniveaudegsco', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('nomLongNiveauDgesco', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Orientation as Orientations', array(
             'local' => 'id',
             'foreign' => 'niveaudgesco_id'));
    }
}