<?php

/**
 * BaseNiveauscolaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nomniveauscolaire
 * @property string $nomLongNiveauScolaire
 * @property string $degreetabsco
 * @property integer $ordre
 * @property Doctrine_Collection $Orientations
 * 
 * @method string              getNomniveauscolaire()      Returns the current record's "nomniveauscolaire" value
 * @method string              getNomLongNiveauScolaire()  Returns the current record's "nomLongNiveauScolaire" value
 * @method string              getDegreetabsco()           Returns the current record's "degreetabsco" value
 * @method integer             getOrdre()                  Returns the current record's "ordre" value
 * @method Doctrine_Collection getOrientations()           Returns the current record's "Orientations" collection
 * @method Niveauscolaire      setNomniveauscolaire()      Sets the current record's "nomniveauscolaire" value
 * @method Niveauscolaire      setNomLongNiveauScolaire()  Sets the current record's "nomLongNiveauScolaire" value
 * @method Niveauscolaire      setOrdre()                  Sets the current record's "ordre" value
 * @method Niveauscolaire      setDegreetabsco()           Sets the current record's "degreetabsco" value
 * @method Niveauscolaire      setOrientations()           Sets the current record's "Orientations" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNiveauscolaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('niveauscolaire');
        $this->hasColumn('nomniveauscolaire', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('nomLongNiveauScolaire', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
		$this->hasColumn('degreetabsco', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
		$this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Orientation as Orientations', array(
             'local' => 'id',
             'foreign' => 'niveauscolaire_id'));
    }
}