<?php

/**
 * BaseDgesco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eleve_id
 * @property integer $anneescolaire_id
 * @property integer $reponse_id
 * @property integer $question_id
 * @property string $libelle_reponse
 * @property Eleve $Eleve
 * @property Anneescolaire $Anneescolaire
 * @property Question $Question
 * @property Reponse $Reponse
 * 
 * @method integer       getEleveId()          Returns the current record's "eleve_id" value
 * @method integer       getAnneescolaireId()  Returns the current record's "anneescolaire_id" value
 ***** @method integer   getReponseId()    Returns the current record's "reponse_id" value
 * @method integer       getQuestionId()       Returns the current record's "question_id" value
 * @method string        getLibelleReponse()   Returns the current record's "libelle_reponse" value
 * @method Eleve         getEleve()            Returns the current record's "Eleve" value
 * @method Anneescolaire getAnneescolaire()    Returns the current record's "Anneescolaire" value
 * @method Question      getQuestion()         Returns the current record's "Question" value
 ***** @method Reponse       getReponse()      Returns the current record's "Reponse" value
 * @method Dgesco        setEleveId()          Sets the current record's "eleve_id" value
 * @method Dgesco        setAnneescolaireId()  Sets the current record's "anneescolaire_id" value
 ***** @method Dgesco        setReponseId()    Sets the current record's "reponse_id" value
 * @method Dgesco        setQuestionId()       Sets the current record's "question_id" value
 * @method Dgesco        setLibelleReponse()   Sets the current record's "libelle_reponse" value
 * @method Dgesco        setEleve()            Sets the current record's "Eleve" value
 * @method Dgesco        setAnneescolaire()    Sets the current record's "Anneescolaire" value
 * @method Dgesco        setQuestion()         Sets the current record's "Question" value
 ***** @method Dgesco    setReponse()          Sets the current record's "Reponse" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDgesco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dgesco');
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('anneescolaire_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
      
        $this->hasColumn('reponse_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
      
       
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('libelle_reponse', 'string', 200, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));

        $this->hasOne('Anneescolaire', array(
             'local' => 'anneescolaire_id',
             'foreign' => 'id'));

        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id'));
	
        $this->hasOne('Reponse', array(
             'local' => 'reponse_id',
             'foreign' => 'id'));
    
              
    }
}
