<?php

/**
 * BasePositionAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contratavs_id
 * @property integer $typepositionavs_id
 * @property date $datedebut
 * @property date $datefin
 * @property ContratAvs $ContratAvs
 * @property TypePositionAvs $TypePositionAvs
 * 
 * @method integer         getContratavsId()       Returns the current record's "contratavs_id" value
 * @method integer         getTypepositionavsId()  Returns the current record's "typepositionavs_id" value
 * @method date            getDatedebut()          Returns the current record's "datedebut" value
 * @method date            getDatefin()            Returns the current record's "datefin" value
 * @method ContratAvs      getContratAvs()         Returns the current record's "ContratAvs" value
 * @method TypePositionAvs getTypePositionAvs()    Returns the current record's "TypePositionAvs" value
 * @method PositionAvs     setContratavsId()       Sets the current record's "contratavs_id" value
 * @method PositionAvs     setTypepositionavsId()  Sets the current record's "typepositionavs_id" value
 * @method PositionAvs     setDatedebut()          Sets the current record's "datedebut" value
 * @method PositionAvs     setDatefin()            Sets the current record's "datefin" value
 * @method PositionAvs     setContratAvs()         Sets the current record's "ContratAvs" value
 * @method PositionAvs     setTypePositionAvs()    Sets the current record's "TypePositionAvs" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePositionAvs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('position_avs');
        $this->hasColumn('contratavs_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('typepositionavs_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('datedebut', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContratAvs', array(
             'local' => 'contratavs_id',
             'foreign' => 'id'));

        $this->hasOne('TypePositionAvs', array(
             'local' => 'typepositionavs_id',
             'foreign' => 'id'));
    }
}