<?php

/**
 * BaseTransport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelletransport
 * @property date $datedebut
 * @property date $datefin
 * @property Doctrine_Collection $DemandeTransports
 * @property Doctrine_Collection $Transportobtenu
 * 
 * @method string              getLibelletransport()  Returns the current record's "libelletransport" value
 * @method date                getDatedebut()         Returns the current record's "datedebut" value
 * @method date                getDatefin()           Returns the current record's "datefin" value
 * @method Doctrine_Collection getDemandeTransports() Returns the current record's "DemandeTransports" collection
 * @method Doctrine_Collection getTransportobtenu()   Returns the current record's "Transportobtenu" collection
 * @method Transport           setLibelletransport()  Sets the current record's "libelletransport" value
 * @method Transport           setDatedebut()         Sets the current record's "datedebut" value
 * @method Transport           setDatefin()           Sets the current record's "datefin" value
 * @method Transport           setDemandeTransports() Sets the current record's "DemandeTransports" collection
 * @method Transport           setTransportobtenu()   Sets the current record's "Transportobtenu" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transport');
        $this->hasColumn('libelletransport', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('datedebut', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeTransport as DemandeTransports', array(
             'local' => 'id',
             'foreign' => 'transport_id'));

        $this->hasMany('Transportobtenu', array(
             'local' => 'id',
             'foreign' => 'transport_id'));
    }
}