<?php

/**
 * BaseTransportobtenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $transport_id
 * @property integer $eleve_id
 * @property integer $demandetransport_id
 * @property date $datedebut
 * @property date $datefin
 * @property DemandeTransport $DemandeTransport
 * @property Transport $Transport
 * @property Eleve $Eleve
 * 
 * @method integer          getTransportId()         Returns the current record's "transport_id" value
 * @method integer          getEleveId()             Returns the current record's "eleve_id" value
 * @method integer          getDemandetransportId()  Returns the current record's "demandetransport_id" value
 * @method date             getDatedebut()           Returns the current record's "datedebut" value
 * @method date             getDatefin()             Returns the current record's "datefin" value
 * @method DemandeTransport getDemandeTransport()    Returns the current record's "DemandeTransport" value
 * @method Transport        getTransport()           Returns the current record's "Transport" value
 * @method Eleve            getEleve()               Returns the current record's "Eleve" value
 * @method Transportobtenu  setTransportId()         Sets the current record's "transport_id" value
 * @method Transportobtenu  setEleveId()             Sets the current record's "eleve_id" value
 * @method Transportobtenu  setDemandetransportId()  Sets the current record's "demandetransport_id" value
 * @method Transportobtenu  setDatedebut()           Sets the current record's "datedebut" value
 * @method Transportobtenu  setDatefin()             Sets the current record's "datefin" value
 * @method Transportobtenu  setDemandeTransport()    Sets the current record's "DemandeTransport" value
 * @method Transportobtenu  setTransport()           Sets the current record's "Transport" value
 * @method Transportobtenu  setEleve()               Sets the current record's "Eleve" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransportobtenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transportobtenu');
        $this->hasColumn('transport_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('eleve_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('demandetransport_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('datedebut', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DemandeTransport', array(
             'local' => 'demandetransport_id',
             'foreign' => 'id'));

        $this->hasOne('Transport', array(
             'local' => 'transport_id',
             'foreign' => 'id'));

        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));
    }
}