<?php

/**
 * BaseEtabnonsco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quartier_id
 * @property integer $typeetablissement_id
 * @property string $nometabnonsco
 * @property string $adresseetabnonscobat
 * @property string $adresseetabnonscorue
 * @property string $teletabnonsco
 * @property string $faxetabnonsco
 * @property string $emailetabnonsco
 * @property integer $ordre
 * @property Typeetablissementnonsco $Typeetablissementnonsco
 * @property Quartier $Quartier
 * @property Doctrine_Collection $Modnonscos
 * @property Doctrine_Collection $Sessads
 * 
 * @method integer             getQuartierId()           Returns the current record's "quartier_id" value
 * @method integer             getTypeetablissementId()  Returns the current record's "typeetablissement_id" value
 * @method string              getNometabnonsco()        Returns the current record's "nometabnonsco" value
 * @method string              getAdresseetabnonscobat() Returns the current record's "adresseetabnonscobat" value
 * @method string              getAdresseetabnonscorue() Returns the current record's "adresseetabnonscorue" value
 * @method string              getTeletabnonsco()        Returns the current record's "teletabnonsco" value
 * @method string              getFaxetabnonsco()        Returns the current record's "faxetabnonsco" value
 * @method string              getEmailetabnonsco()      Returns the current record's "emailetabnonsco" value
 * @method integer             getOrdre()                  Returns the current record's "ordre" value
 * @method Quartier            getQuartier()             Returns the current record's "Quartier" value
 * @method Typeetablissementnonsco   getTypeetablissementnonsco()    Returns the current record's "Typeetablissementnonsco" value
 * @method Doctrine_Collection getModnonscos()           Returns the current record's "Modnonscos" collection
 * @method Doctrine_Collection getSessads()              Returns the current record's "Sessads" collection
 * @method Etabnonsco          setQuartierId()           Sets the current record's "quartier_id" value
 * @method integer             setTypeetablissementId()  Sets the current record's "typeetablissement_id" value
 * @method Etabnonsco          setNometabnonsco()        Sets the current record's "nometabnonsco" value
 * @method Etabnonsco          setAdresseetabnonscobat() Sets the current record's "adresseetabnonscobat" value
 * @method Etabnonsco          setAdresseetabnonscorue() Sets the current record's "adresseetabnonscorue" value
 * @method Etabnonsco          setTeletabnonsco()        Sets the current record's "teletabnonsco" value
 * @method Etabnonsco          setFaxetabnonsco()        Sets the current record's "faxetabnonsco" value
 * @method Etabnonsco          setEmailetabnonsco()      Sets the current record's "emailetabnonsco" value
 * @method Etabnonsco          setOrdre()                  Sets the current record's "ordre" value
 * @method Etabnonsco          setQuartier()             Sets the current record's "Quartier" value
 * @method Typeetablissementnonsco   setTypeetablissementnonsco()  Sets the current record's "Typeetablissementnonsco" value
 * @method Etabnonsco          setModnonscos()           Sets the current record's "Modnonscos" collection
 * @method Etabnonsco          setSessads()              Sets the current record's "Sessads" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEtabnonsco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('etabnonsco');
        $this->hasColumn('quartier_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

		$this->hasColumn('typeetablissement_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nometabnonsco', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('adresseetabnonscobat', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('adresseetabnonscorue', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('teletabnonsco', 'string', 10, array(
             'type' => 'string',
             'regexp' => '/^([\\s]*[0-9]+[\\s]*)+$/',
             'length' => 10,
             ));
        $this->hasColumn('faxetabnonsco', 'string', 10, array(
             'type' => 'string',
             'regexp' => '/^([\\s]*[0-9]+[\\s]*)+$/',
             'length' => 10,
             ));
        $this->hasColumn('emailetabnonsco', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
		$this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
			 'notnull' => false,
              ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quartier', array(
             'local' => 'quartier_id',
             'foreign' => 'id'));
			 
		$this->hasOne('Typeetablissementnonsco', array(
             'local' => 'typeetablissement_id',
             'foreign' => 'id'));

        $this->hasMany('Modnonsco as Modnonscos', array(
             'local' => 'id',
             'foreign' => 'etabnonsco_id'));

        $this->hasMany('Sessad as Sessads', array(
             'local' => 'id',
             'foreign' => 'etabnonsco_id'));
    }
}