<?php

/**
 * BaseQuartier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $commune_id
 * @property string $code_postal
 * @property string $nom_quartier
 * @property Commune $Commune
 * @property Doctrine_Collection $Eleve
 * @property Doctrine_Collection $Etabnonscos
 * @property Doctrine_Collection $Etabscos
 * @property Doctrine_Collection $Personnes
 * 
 * @method integer             getCommuneId()    Returns the current record's "commune_id" value
 * @method string              getCodePostal()   Returns the current record's "code_postal" value
 * @method string              getNomQuartier()  Returns the current record's "nom_quartier" value
 * @method Commune             getCommune()      Returns the current record's "Commune" value
 * @method Doctrine_Collection getEleve()        Returns the current record's "Eleve" collection
 * @method Doctrine_Collection getEtabnonscos()  Returns the current record's "Etabnonscos" collection
 * @method Doctrine_Collection getEtabscos()     Returns the current record's "Etabscos" collection
 * @method Doctrine_Collection getPersonnes()    Returns the current record's "Personnes" collection
 * @method Quartier            setCommuneId()    Sets the current record's "commune_id" value
 * @method Quartier            setCodePostal()   Sets the current record's "code_postal" value
 * @method Quartier            setNomQuartier()  Sets the current record's "nom_quartier" value
 * @method Quartier            setCommune()      Sets the current record's "Commune" value
 * @method Quartier            setEleve()        Sets the current record's "Eleve" collection
 * @method Quartier            setEtabnonscos()  Sets the current record's "Etabnonscos" collection
 * @method Quartier            setEtabscos()     Sets the current record's "Etabscos" collection
 * @method Quartier            setPersonnes()    Sets the current record's "Personnes" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuartier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quartier');
        $this->hasColumn('commune_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('code_postal', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 5,
             ));
        $this->hasColumn('nom_quartier', 'string', 70, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 70,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Commune', array(
             'local' => 'commune_id',
             'foreign' => 'id'));

        $this->hasMany('Eleve', array(
             'local' => 'id',
             'foreign' => 'quartier_id'));

        $this->hasMany('Etabnonsco as Etabnonscos', array(
             'local' => 'id',
             'foreign' => 'quartier_id'));

        $this->hasMany('Etabsco as Etabscos', array(
             'local' => 'id',
             'foreign' => 'quartier_id'));

        $this->hasMany('Personne as Personnes', array(
             'local' => 'id',
             'foreign' => 'quartier_id'));
    }
}