<?php

/**
 * BaseMouvement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nommouvement
 * @property Doctrine_Collection $MouvementMateriels
 * 
 * @method string              getNommouvement()       Returns the current record's "nommouvement" value
 * @method Doctrine_Collection getMouvementMateriels() Returns the current record's "MouvementMateriels" collection
 * @method Mouvement           setNommouvement()       Sets the current record's "nommouvement" value
 * @method Mouvement           setMouvementMateriels() Sets the current record's "MouvementMateriels" collection
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMouvement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mouvement');
        $this->hasColumn('nommouvement', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MouvementMateriel as MouvementMateriels', array(
             'local' => 'id',
             'foreign' => 'mouvement_id'));
    }
}