<?php

/**
 * BaseClasseext
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $libelle_classe_ext
 * @property Doctrine_Collection $DemandeOrientations

 * 
 * @method string              getLibelleClasseExt()    Returns the current record's "libelle_classe_ext" value
 * @method Doctrine_Collection getDemandeOrientations() Returns the current record's "DemandeOrientations" collection
 * @method Classeext           setLibelleClasseExt()    Sets the current record's "libelle_classe_ext" value
 * @method Classeext           setDemandeOrientations() Sets the current record's "DemandeOrientations" collection

 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClasseext extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('classeext');
        $this->hasColumn('libelle_classe_ext', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DemandeOrientation as DemandeOrientations', array(
             'local' => 'id',
             'foreign' => 'classeext_id'));

    }
}