<?php

/**
 * BaseSuivitExterne
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $specialiste_id
 * @property integer $eleve_id
 * @property date $datedebutpriseencharge
 * @property date $datefinpriseencharge
 * @property integer $organismesuivit_id
 * @property integer $naturesuiviext_id
 * @property Eleve $Eleve
 * @property OrganismeSuivit $OrganismeSuivit
 * @property Naturesuiviext $Naturesuiviext
 * @property Specialiste $Specialiste
 * 
 * @method integer         getSpecialisteId()          Returns the current record's "specialiste_id" value
 * @method integer         getEleveId()                Returns the current record's "eleve_id" value
 * @method date            getDatedebutpriseencharge() Returns the current record's "datedebutpriseencharge" value
 * @method date            getDatefinpriseencharge()   Returns the current record's "datefinpriseencharge" value
 * @method integer         getOrganismesuivitId()      Returns the current record's "organismesuivit_id" value
 * @method integer         getNaturesuiviextId()       Returns the current record's "naturesuiviext_id" value
 * @method Eleve           getEleve()                  Returns the current record's "Eleve" value
 * @method OrganismeSuivit getOrganismeSuivit()        Returns the current record's "OrganismeSuivit" value
 * @method Naturesuiviext  getNaturesuiviext()         Returns the current record's "Naturesuiviext" value
 * @method Specialiste     getSpecialiste()            Returns the current record's "Specialiste" value
 * @method SuivitExterne   setSpecialisteId()          Sets the current record's "specialiste_id" value
 * @method SuivitExterne   setEleveId()                Sets the current record's "eleve_id" value
 * @method SuivitExterne   setDatedebutpriseencharge() Sets the current record's "datedebutpriseencharge" value
 * @method SuivitExterne   setDatefinpriseencharge()   Sets the current record's "datefinpriseencharge" value
 * @method SuivitExterne   setOrganismesuivitId()      Sets the current record's "organismesuivit_id" value
 * @method SuivitExterne   setNaturesuiviextId()       Sets the current record's "naturesuiviext_id" value
 * @method SuivitExterne   setEleve()                  Sets the current record's "Eleve" value
 * @method SuivitExterne   setOrganismeSuivit()        Sets the current record's "OrganismeSuivit" value
 * @method SuivitExterne   setNaturesuiviext()         Sets the current record's "Naturesuiviext" value
 * @method SuivitExterne   setSpecialiste()            Sets the current record's "Specialiste" value
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSuivitExterne extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('suivit_externe');
        $this->hasColumn('specialiste_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('eleve_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('datedebutpriseencharge', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('datefinpriseencharge', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('organismesuivit_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('naturesuiviext_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eleve', array(
             'local' => 'eleve_id',
             'foreign' => 'id'));

        $this->hasOne('OrganismeSuivit', array(
             'local' => 'organismesuivit_id',
             'foreign' => 'id'));

        $this->hasOne('Naturesuiviext', array(
             'local' => 'naturesuiviext_id',
             'foreign' => 'id'));

        $this->hasOne('Specialiste', array(
             'local' => 'specialiste_id',
             'foreign' => 'id'));
    }
}