stylesheets:    [basic.css, basic_ie.css, demo.css]
javascripts:    [ jquery-1.6.2.min.js, basic.js, jquery.simplemodal.js]
aideSuccess:
  has_layout: false
  
  
messageSuccess:
  has_layout: false

popupSuccess:
  has_layout: true
  layout:     layoutpopup

