<?php

/**
 * Avs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ash974
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Avs extends BaseAvs
{

   static public function format_tel($field){  //formattage numéro de téléphone : 0692 02 02 02
   if (strlen($field) == 10 ){
  	return substr($field,0,4). ' '.substr($field,4,2). ' '.substr($field,6,2).' '.substr($field,8,2);
	}else{
	return $field;
	}
  }
    static public function capitalize($field){  //mettre en majuscule
 setlocale(LC_CTYPE, 'fr_FR.UTF8');
return mb_strtoupper($field, 'UTF-8'); 
  }
	public function __toString(){
		// on retourne les nom et prenom de l'avs
		return $this->getNom()." ".$this->getPrenom();
    }
        
	public function getContratAvsValid()
	{
		 $anneeScolaire = Doctrine_Core::getTable('Anneescolaire')
							->getAnneeScolaireEnCours();
		 $contratAvss = $this->getContratAvs(); // On suppose qu'une avs n'a pas signé 2 contrats et saisis dans cette application
		 
		 foreach ($contratAvss as $contratAvs)
		 {
			  if ($contratAvs->getDateFinContrat() > $anneeScolaire->getDatedebutanneescolaire())
			   return $contratAvs;
			   
	     }
	      return null;
	}
	
  public function getAvscontratenCours() {

   $eleve_cda = Doctrine_Core::getTable('Avs')->getAvecContratenCours();
   return $this->getNom().' '.$this->getPrenom().' - temps hebdo : '.$this->getTempsHebdo().'heure(s) - contrat du '.date('d/m/Y',strtotime($this->getDateDebutContrat())).' au '.date('d/m/Y',strtotime($this->getDateFinContrat()));
}

}
