<?php

/**
 * AvsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Avs');
    }

/** * Cette fonction filtre les avs qui ont de contrat valide pour un etablissement donné
* @param type $etabsco_id * @return object AvsTable 
* 
* */
public function getAvsValidEtabsco($circonscription_id)
   {
       $anneeScolaire =	Doctrine_Core::getTable('Anneescolaire')->getAnneeScolaireEnCours();
       $qs = Doctrine_Query::create()
               ->from('Etabsco e')
               ->select('e.id,e.typeetablissement_id,e.nometabsco')
               ->where('e.circonscription_id=?', $circonscription_id)
			   	->orderBy('e.typeetablissement_id,e.nometabsco')
               ->execute();
       $i = 0;
       $etabscIds = array();
       foreach ($qs as $q)
       {
           $etabscIds[$i] = $q->getId();
           $i++;
       }
       return $this->getInstance()->createQuery('av')
                       ->innerJoin('av.ContratAvs ca')
                       ->where('ca.date_fin_contrat > ?',$anneeScolaire->getDatedebutanneescolaire())
                       ->andWhereIn('ca.etabsco_id', $etabscIds);
   }
	 
	 public function getAvsValidEtabscoId($id, $etabsco_id, $naturecontratavs_id)
	 {
		  $avs = $this->getAvsValidEtabsco($etabsco_id, $naturecontratavs_id)
							->where('id = ?', $id)
							->execute();
							
		  return $avs[0];
	 }
	 


		  public function getAvecContratenCours()
	 {
	       $q = Doctrine_Query::Create()
		  ->select ('a.nom as nom,c.date_debut_contrat as date_debut_contrat,c.date_fin_contrat as date_fin_contrat,c.commentaire as commentaire,c.temps_hebdo as temps_hebdo')
          ->from('Avs a')
		  ->innerjoin('a.ContratAvss c ON a.id = c.avs_id')
          ->where('c.date_fin_contrat > DATE(NOW())')
          ->orderby ('a.nom,a.prenom');
		  return $q;
		 }	 

}
