<?php

/**
 * CirconscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CirconscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CirconscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Circonscription');
    }
}