<?php

/**
 * ClassespeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassespeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClassespeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Classespe');
    }
}