<?php

/**
 * ConditionsuspensiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConditionsuspensiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConditionsuspensiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conditionsuspensive');
    }
}