<?php

/**
 * DemandeSessadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DemandeSessadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DemandeSessadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DemandeSessad');
    }
	public function getDemandeSessadSelectionner($demandesessad_id)
	{
	
	//Dernière demande de sessad avec décision CDA pour la demande sélectionnée
	//------------------------------------------------------------------------
			$q = $this->createQuery('c')
			->select('t.id as typesessad_id, m.eleve_id as eleve_id, m.id as MdphId, d.id as demandesessad_id, 
			 m.datecreationpps as datecreationpps, m.dateess as dateess, m.dateenvoiedossier as dateenvoiedossier,t.libelletypesessad as libelletypesessad,
			 d.datefinnotif as datefinnotif,d.datedebutnotif as datedebutnotif,d.datedecisioncda as datedecisioncda')
			->from('DemandeSessad d')
			->leftJoin('d.Mdph m ON d.mdph_id = m.id')
			->leftJoin('d.Typesessad t ON t.id = d.typesessad_id')
			->where('d.id=?',$demandesessad_id) ;

			return $q->fetchArray();
	
	}
	
	public function getDemandeSessaddroitouvert($eleveId)
	{
	       //  demande sessad droit ouvert
          //--------------------------------
               $q = $this->createQuery('c')  
                -> select ('t.id as typesessad_id, m.eleve_id as eleve_id, m.id as MdphId, a.id as demandesessad_id, 
			 m.datecreationpps as datecreationpps, m.dateess as dateess, m.dateenvoiedossier as dateenvoiedossier,t.libelletypesessad as libelletypesessad,
			 a.datefinnotif as datefinnotif,a.datedebutnotif as datedebutnotif,a.datedecisioncda as datedecisioncda,DATE_ADD( a.datefinnotif , INTERVAL -6 MONTH ) as date_fin_projete')
                -> from('DemandeSessad a')
                ->innerJoin('a.Typesessad t ON a.typesessad_id = t.id')
				->innerjoin('a.Mdph m on m.id = a.mdph_id')
				->where('m.eleve_id=?',$eleveId)
				->andwhere('a.datedebutnotif <=?',date('Y-m-d', time()))
			    ->andWhere('a.datefinnotif >=?', date('Y-m-d', time()))
			    ->orderby('a.id desc');
		        return $q->fetchArray();
	}
	
		public function getDemandeSessadencour($eleveId)
    {
	      // demande sessad droit en cours
          //--------------------------------
               $q = $this->createQuery('c')  
                -> select ('t.id as typesessad_id, m.eleve_id as eleve_id, m.id as MdphId, a.id as demandesessad_id, 
			 m.datecreationpps as datecreationpps, m.dateess as dateess, m.dateenvoiedossier as dateenvoiedossier,t.libelletypesessad as libelletypesessad,
			 a.datefinnotif as datefinnotif,a.datedebutnotif as datedebutnotif,a.datedecisioncda as datedecisioncda')
                -> from('DemandeSessad a')
                ->innerJoin('a.Typesessad t ON a.typesessad_id = t.id')
				->innerjoin('a.Mdph m on m.id = a.mdph_id')
				->where('m.eleve_id=?',$eleveId)
				->andwhere ('a.datedecisioncda is null')
			    ->orderby('a.id desc');
		       return $q->fetchArray();
	}
	
		public function getDemandeSessaddroitouvert6mois($eleveId)
	{
	       //  demande sessad droit ouvert
          //--------------------------------
               $q = $this->createQuery('c')  
                -> select ('t.id as typesessad_id, m.eleve_id as eleve_id, m.id as MdphId, a.id as demandesessad_id, 
			 m.datecreationpps as datecreationpps, m.dateess as dateess, m.dateenvoiedossier as dateenvoiedossier,t.libelletypesessad as libelletypesessad,
			 a.datefinnotif as datefinnotif,a.datedebutnotif as datedebutnotif,a.datedecisioncda as datedecisioncda,DATE_ADD( a.datefinnotif , INTERVAL -6 MONTH ) as date_fin_projete')
                -> from('DemandeSessad a')
                ->innerJoin('a.Typesessad t ON a.typesessad_id = t.id')
				->innerjoin('a.Mdph m on m.id = a.mdph_id')
				->where('m.eleve_id=?',$eleveId)
				->andwhere('a.datedebutnotif <=?',date('Y-m-d', time()))
			    ->andWhere('a.datefinnotif >=?', date('Y-m-d', time()))
			    ->andWhere('DATE_ADD( a.datefinnotif , INTERVAL -6 MONTH ) <=?', date('Y-m-d', time()))
			    ->orderby('a.id desc');
		        return $q->fetchArray();
	}
	
}