<?php

/**
 * DemandeAvsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DemandeAvsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DemandeAvsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DemandeAvs');
    }
	
	public function getDerDemandeAcc($eleve_id)
	{
	//Dernière demande AVS en cours à la date du jour pour l'élève selectionné
	//-----------------------------------------------------------------------
	
			$res = Doctrine_Query::create()
			->select('max(m.id) as max_mdph_id,max(d.id) as max_demavs_id,m.eleve_id as eleve_id')
			->from('Mdph m')
			->innerJoin('m.DemandeAvss d ON m.id = d.mdph_id')
			->groupBy('m.eleve_id')
			->having('m.eleve_id=?',$eleve_id) 
			->fetchArray();
	    

          if ($res[0]['max_demavs_id']){	
			
			$q = $this->createQuery('c')
			->Select('d.id as DemandeAvsId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			d.quotitehorrairenotifie as quotitehorrairenotifie,naturecontrat as naturecontrat, d.decisioncda as decisioncda')
			->from('DemandeAvs d')
			->innerJoin('d.Mdph m ON m.id = d.mdph_id')
			->leftJoin('d.Naturecontratavs n ON d.naturecontratavs_id = n.id')
			->where('d.datedecisioncda IS NOT NULL')
			->where ('m.eleve_id=?',$eleve_id)
			->andwhere ('d.id=?',$res[0]['max_demavs_id'])
			->andWhere('d.datefinnotif >= ?', date('Y-m-d', time()))
			->whereIn('d.id',$res[0]['max_demavs_id'])		
			->groupby ('d.id');
		
			return $q->fetchArray();
			}
		}
		public function getListDerDemandeAcc($eleve_id)
	{
	//liste des Dernières demande AVS en cours à la date du jour pour l'élève selectionné
	//------------------------------------------------------------------------------------
	
			$q = $this->createQuery('c')
			->Select('d.id as DemandeAvsId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			d.quotitehorrairenotifie as quotitehorrairenotifie,naturecontrat as naturecontrat, d.decisioncda as decisioncda,co.conditionsuspensive as conditionsuspensive')
			->from('DemandeAvs d')
			->innerJoin('d.Mdph m ON m.id = d.mdph_id')
			->leftJoin('d.Naturecontratavs n ON d.naturecontratavs_id = n.id')
			->leftJoin('d.Conditionsuspensive co ON co.id = d.conditionsuspensive_id')
			->where('d.datedecisioncda IS NOT NULL')
			->where('m.eleve_id=?',$eleve_id)
			->andWhere('d.datefinnotif >=?', date('Y-m-d', time()));
			//->Orderby('datefinnotif,datedebutnotif');
			return $q->fetchArray();
	
		}		
	public function getListDemandeAccCDA($eleve_id)
	{
	//Dernière demande AVS en attente décision CDA pour l'élève selectionné
	//-----------------------------------------------------------------------
	
			$q = $this->createQuery('c')
			->Select('d.id as DemandeAvsId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			d.quotitehorrairenotifie as quotitehorrairenotifie,naturecontrat as naturecontrat')
			->from('DemandeAvs d')
			->innerJoin('d.Mdph m ON m.id = d.mdph_id')
			->leftJoin('d.Naturecontratavs n ON d.naturecontratavs_id = n.id')
			->where('d.datedecisioncda is NULL')
			->andwhere('m.eleve_id=?',$eleve_id);

			return $q->fetchArray();
			
			
								
	}
	
	  	public function getHistoDemandeAvs($eleve_id)
		// historique des demandes d'avs traité pour un élève
		{
	       $q = $this->createQuery('c')
			->Select('d.id as DemandeAvsId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			d.decisioncda as decisioncda,d.quotitehorrairenotifie as quotitehorrairenotifie,naturecontrat as naturecontrat,e.etat_acc as etat_acc,e.nom as nom,e.prenom as prenom,e.datenaissance as datenaissance')
			->from('DemandeAvs d')
			->innerJoin('d.Mdph m ON m.id = d.mdph_id')
			->innerJoin('m.Eleve e ON e.id = m.eleve_id')
			->leftJoin('d.Naturecontratavs n ON d.naturecontratavs_id = n.id')
			->where('d.datedecisioncda IS NOT NULL')
			->andwhere('m.eleve_id=?',$eleve_id);
			return $q->fetchArray();
			}
			
		public function getDemandeAvsdroitouvert($eleveId)
		// demande d'AVS droit ouvert
       //----------------------------
		{
	       $q = $this->createQuery('c')
				->select('d.id as DemandeAvsId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			d.quotitehorrairenotifie as quotitehorrairenotifie,naturecontrat as naturecontrat, d.decisioncda as decisioncda')
                -> from('DemandeAvs d')
				->innerJoin('d.Mdph m ON d.mdph_id = m.id')
                ->innerJoin('m.Eleve e ON m.eleve_id = e.id')
			    ->leftJoin('d.Naturecontratavs n ON d.naturecontratavs_id = n.id')
 			  	->where('m.eleve_id=?',$eleveId)
                ->andwhere('d.datedebutnotif <=?',date('Y-m-d', time()))
			    ->andWhere('d.datefinnotif >=?', date('Y-m-d', time()));
			return $q->fetchArray();
			}
			

			
			
	   public function getDemandeAvsencour($eleveId)
		// demande d'AVS en cours
       //----------------------------
		{
	       $q = $this->createQuery('c')
				->select('d.id as DemandeAvsId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			d.quotitehorrairenotifie as quotitehorrairenotifie,naturecontrat as naturecontrat, d.decisioncda as decisioncda,m.dateenvoiedossier as dateenvoiedossier ')
                -> from('DemandeAvs d')
				->innerJoin('d.Mdph m ON d.mdph_id = m.id')
                ->innerJoin('m.Eleve e ON m.eleve_id = e.id')
			    ->leftJoin('d.Naturecontratavs n ON d.naturecontratavs_id = n.id')
 			  	->where('m.eleve_id=?',$eleveId)
                ->andwhere ('d.datedecisioncda is null');
			return $q->fetchArray();
			}
			
		public function getDemandeAvsdroitouvert6mois($eleveId)
		// demande d'AVS droit ouvert
       //----------------------------
		{
	       $q = $this->createQuery('c')
				->select('d.id as DemandeAvsId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			d.quotitehorrairenotifie as quotitehorrairenotifie,naturecontrat as naturecontrat, d.decisioncda as decisioncda,,DATE_ADD( d.datefinnotif , INTERVAL -6 MONTH ) as date_fin_projete')
                -> from('DemandeAvs d')
				->innerJoin('d.Mdph m ON d.mdph_id = m.id')
                ->innerJoin('m.Eleve e ON m.eleve_id = e.id')
			    ->leftJoin('d.Naturecontratavs n ON d.naturecontratavs_id = n.id')
 			  	->where('m.eleve_id=?',$eleveId)
                ->andwhere('d.datedebutnotif <=?',date('Y-m-d', time()))
				->andWhere('DATE_ADD( d.datefinnotif , INTERVAL -6 MONTH ) <=?', date('Y-m-d', time()))
			    ->andWhere('d.datefinnotif >=?', date('Y-m-d', time()));
			return $q->fetchArray();
			}
			
	
}
