<?php

/**
 * DemandeOrientationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DemandeOrientationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DemandeOrientationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DemandeOrientation');
    }
	
		public function getDemandeorientationdroitouvert($eleveId)
		// demande d'orientation droit ouvert
       //------------------------------------
		{
	       $q = $this->createQuery('c')
				->select('d.id as DemandeorientationId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			, d.decisioncda as decisioncda,c.libelle_classe_ext as libelleclasseext')
                -> from('DemandeOrientation d')
				->innerJoin('d.Mdph m ON d.mdph_id = m.id')
                ->innerJoin('m.Eleve e ON m.eleve_id = e.id')
			    ->leftjoin('d.Classeext c ON d.classeext_id = c.id')
 			  	->where('m.eleve_id=?',$eleveId)
				->andwhere ('d.decisioncda= true')
                ->andwhere('d.datedebutnotif <=?',date('Y-m-d', time()))
			    ->andWhere('d.datefinnotif >=?', date('Y-m-d', time()));
				
			return $q->fetchArray();
			}
			
		public function getDemandeorientationencour($eleveId)
		// demande d'orientation en cour
       //--------------------------------	
	   {
	       $q = $this->createQuery('c')
				->select('d.id as DemandeorientationId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			, d.decisioncda as decisioncda,c.libelle_classe_ext as libelleclasseext')
                -> from('DemandeOrientation d')
				->innerJoin('d.Mdph m ON d.mdph_id = m.id')
                ->innerJoin('m.Eleve e ON m.eleve_id = e.id')
			    ->leftJoin('d.Classeext c ON d.classeext_id = c.id')
 			  	->where('m.eleve_id=?',$eleveId)
				->andwhere ('d.datedecisioncda is null');
			return $q->fetchArray();
			}
			
			
		public function getDemandeorientationdroitouvert6mois($eleveId)
		// demande d'orientation droit ouvert
       //------------------------------------
		{
	       $q = $this->createQuery('c')
				->select('d.id as DemandeorientationId,m.id as MdphId,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,d.datedecisioncda as datedecisioncda,
			, d.decisioncda as decisioncda,c.libelle_classe_ext as libelleclasseext,DATE_ADD( d.datefinnotif , INTERVAL -6 MONTH ) as date_fin_projete')
                -> from('DemandeOrientation d')
				->innerJoin('d.Mdph m ON d.mdph_id = m.id')
                ->innerJoin('m.Eleve e ON m.eleve_id = e.id')
			    ->leftjoin('d.Classeext c ON d.classeext_id = c.id')
 			  	->where('m.eleve_id=?',$eleveId)
				->andwhere ('d.decisioncda= true')
                ->andwhere('d.datedebutnotif <=?',date('Y-m-d', time()))
				 ->andWhere('DATE_ADD( d.datefinnotif , INTERVAL -6 MONTH ) <=?', date('Y-m-d', time()))
			    ->andWhere('d.datefinnotif >=?', date('Y-m-d', time()));
				
			return $q->fetchArray();
			}
}