<?php

/**
 * DemandeTransportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DemandeTransportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DemandeTransportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DemandeTransport');
    }
		public function getDemandetransportSelectionner($demandetransport_id)
	{
	
	//Dernière demande de transport avec décision CDA pour la demande sélectionnée
	//------------------------------------------------------------------------
			$q = $this->createQuery('c')
			->select('t.id as typesessad_id, m.eleve_id as eleve_id, m.id as MdphId, d.id as demandetransport_id, 
			 m.datecreationpps as datecreationpps, m.dateess as dateess, m.dateenvoiedossier as dateenvoiedossier,t.libelletransport as libelletransport,
			 d.datefinnotif as datefinnotif,d.datedebutnotif as datedebutnotif,d.datedecisioncda as datedecisioncda')
			->from('DemandeTransport d')
			->leftJoin('d.Mdph m ON d.mdph_id = m.id')
			->leftJoin('d.Transport t ON t.id = d.transport_id')
			->where('d.id=?',$demandetransport_id) ;

			return $q->fetchArray();
	
	}
	public function getDemandetransportdroitouvert($eleveId)
	{
	
	//Dernière demande de transport avec décision CDA pour la demande sélectionnée
	//------------------------------------------------------------------------
			$q = $this->createQuery('c')
				->select('t.id as typesessad_id, m.eleve_id as eleve_id, m.id as MdphId, d.id as demandetransport_id, 
			 m.datecreationpps as datecreationpps, m.dateess as dateess, m.dateenvoiedossier as dateenvoiedossier,t.libelletransport as libelletransport,
			 d.datefinnotif as datefinnotif,d.datedebutnotif as datedebutnotif,d.datedecisioncda as datedecisioncda')
                -> from('DemandeTransport d')
                ->innerJoin('d.Transport t ON d.transport_id = t.id')
				->innerjoin('d.Mdph m on m.id = d.mdph_id')
				->where('m.eleve_id=?',$eleveId)
				->andwhere('d.datedebutnotif <=?',date('Y-m-d', time()))
			   ->andWhere('d.datefinnotif >=?', date('Y-m-d', time()))
			   ->orderby('d.id desc');
				return $q->fetchArray();
	
	}
	
	public function getDemandetransportencour($eleveId)
	{
	
	//Dernière demande de transport avec décision CDA pour la demande sélectionnée
	//------------------------------------------------------------------------
			$q = $this->createQuery('c')
				->select('*')
                -> from('DemandeTransport d')
                ->innerJoin('d.Transport t ON d.transport_id = t.id')
				->innerjoin('d.Mdph m on m.id = d.mdph_id')
				->where('m.eleve_id=?',$eleveId)
				->andwhere ('d.datedecisioncda is null')
			   ->orderby('d.id desc');

			return $q->fetchArray();
	
	}
	
	
		public function getDemandetransportdroitouvert6mois($eleveId)
	{
	
	//Dernière demande de transport avec décision CDA pour la demande sélectionnée
	//------------------------------------------------------------------------
			$q = $this->createQuery('c')
				->select('t.id as typesessad_id, m.eleve_id as eleve_id, m.id as MdphId, d.id as demandetransport_id, 
			 m.datecreationpps as datecreationpps, m.dateess as dateess, m.dateenvoiedossier as dateenvoiedossier,t.libelletransport as libelletransport,
			 d.datefinnotif as datefinnotif,d.datedebutnotif as datedebutnotif,d.datedecisioncda as datedecisioncda,DATE_ADD( d.datefinnotif , INTERVAL -6 MONTH ) as date_fin_projete')
                -> from('DemandeTransport d')
                ->innerJoin('d.Transport t ON d.transport_id = t.id')
				->innerjoin('d.Mdph m on m.id = d.mdph_id')
				->where('m.eleve_id=?',$eleveId)
				->andwhere('d.datedebutnotif <=?',date('Y-m-d', time()))
			   ->andWhere('d.datefinnotif >=?', date('Y-m-d', time()))
			     ->andWhere('DATE_ADD( d.datefinnotif , INTERVAL -6 MONTH ) <=?', date('Y-m-d', time()))
			   ->orderby('d.id desc');
				return $q->fetchArray();
	
	}
	

}
