<?php

/**
 * DemijourneeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DemijourneeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DemijourneeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Demijournee');
    }
}