<?php

/**
 * DetailCommandeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetailCommandeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetailCommandeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetailCommande');
    }
}