<?php

/**
 * Dgesco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Dgesco extends BaseDgesco
{

 
		public function decryptage($reponse,$clef){
		// les données sont cryptées sur la base de données, on les décrypte
		$encryption_key = $clef;
		return trim(mcrypt_decrypt(MCRYPT_RIJNDAEL_256, $encryption_key, base64_decode($reponse), MCRYPT_MODE_ECB, mcrypt_create_iv(mcrypt_get_iv_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_ECB), MCRYPT_RAND)));
	}	
}
