<?php

/**
 * DgescoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DgescoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DgescoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dgesco');
    }
	
	
	
	 public function cryptage() {
		// on crypte le champ reponse
		$data = $this->getReponse();
		// -- creation d'une clef unique et temporaire (une par / an)
		
		try {
				$options = Array (
					'encryption_key' => '123456',
					'data_to_encrypt' => $data
				);
		
			$e = new AES($options);
			$enc = $e->encrypt();
			//$dec = $e->decrypt();
			
			$this->setReponse($enc);
			//echo "The encrypted Base64/AES string is:  ".$enc."<br />The decrypted Base64/AES string is:  ".$dec;
		
		}catch(Exception $e){
			 return $e->getMessage();
		}
	
    } 
}