<?php

/**
 * EleveAvs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ashile
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EleveAvs extends BaseEleveAvs
{
	public function __toString()
	{
		// a completer...
		return $this->getAvsId();
	}
//liste des élèves sans personnel accompagnant
//---------------------------------------------
	public function getEleveSansAcc()
	{
	            $q = createQuery('c')
                ->select (' e.id as EleveId,e.datenaissance as datenaissance,e.nom as nom,e.prenom as prenom,et.id as etid,o.id as orienid,et.rne as rne,et.nometabsco as etab,t.nomtypeetablissement as typetab,s.libellesecteur as secteur')
                ->from('Eleve e ')
                ->innerjoin('e.Secteur s ON s.id = e.secteur_id')
                ->leftjoin('e.Orientation o ON  e.id =  o.eleve_id')
                ->leftjoin('o.Etabsco et ON  et.id = o.etabsco_id')
                ->innerjoin('et.Typeetablissement t ON t.id = et.typeetablissement_id')
				->Where('e.id NOT IN (select distinct eleve_id from eleve_avs)')
                ->orderby('secteur,nometabsco');
              return $q->fetchArray();
	}
	
	public function getTotal()
	{
	     //Total de la quotité horaire notifiée pour l'élève sélectionné
	    //-----------------------------------------------------------------------
				$q = createQuery('c')
                ->select ('a.eleve_id as avs_id,sum(a.quotitehorraireavs) as quotiteeleve')
                ->from('EleveAvs a')
                ->where('eleve_id = ?', $request->getParameter('eleve_id'))
				->andWhere('a.datefin >=?', date('Y-m-d', time()))
				->groupBy('a.eleve_id');
                 return $q->fetchArray();	
	}
	
	public function getDestinataire()
	{
			$SecteurId = $this->Eleve->getSecteurId();
			$d = Doctrine_Query::Create()
					->select('sfg.id as id, s.id as secteur_id, sfg.email_address')
					->from('Secteur s')
					->leftJoin('s.sfguarduser sfg ON sfg.id = s.sfguarduser_id')
					->where('s.id = ?', $SecteurId);

					
			return $d->execute();
	}

}
