<?php

/**
 * Etabsco
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ash974
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Etabsco extends BaseEtabsco
{   
	public function setUp() {
            parent::setUp();
        $this->hasOne('Typeetablissement', array(
             'local' => 'typeetablissement_id',
             'foreign' => 'id',
			 'orderBy' => 'id' ));
	}
	public function __toString()
	{ 

	    //return Doctrine_Core::getTable('Etabsco')->ListEtab();
		return  $this->getTypeetablissement().' '.$this->getNometabsco().' ( '.$this->getRne().' ) ';
		//return $this->getTypeetablissement().'('.$this->getNometabsco().' - '. $this->getRne().')';

	}

	public function getElevesetabs()
	{
	  $q = Doctrine_Query::create()
	    ->from('Eleve j')
	    ->where('j.etabsco_id = ?', $this->getId());
	 
	  return Doctrine_Core::getTable('Eleve')->getElevesetabs($q);
	}
}
