<?php

/**
 * EtabnonscoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtabnonscoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtabnonscoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Etabnonsco');
    }
}