<?php

/**
 * EtabscoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtabscoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtabscoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Etabsco');
    }
  

	public function getEleves()
	{
		$q = $this->createQuery('c')
			->leftJoin('c.eleves j');

			return $q->execute();
	}

	public function getEtabSecteur()
	{
		/***********************************************
		$secteur = Doctrine::getTable('secteur')
				->findBySfguarduserId($this->getUser()
				->getGuardUser()	
				->getId());
		***********************************************/
		
		//$secteur = sfContext::getInstance()->getUser()->getAttribute('secteur');				 

		$q = Doctrine_Query::create()
			->select('se.etabsco_id')
			->from('Secteur_Etab se')
			->where('se.secteur_id = ?', $secteur->getId());

		return $q->execute();
	}
	
	
	public function getEtabAutocompletion($q, $limit = 30){
    $dq = Doctrine_Query::create()
            ->select('e.id, e.rne,e.nometabsco as nometab,t.nomtypeetablissement as typeetab')
            ->from('etabsco e')
			->innerjoin('e.Typeetablissement t on t.id = e.typeetablissement_id ')
            ->where('CONCAT(e.rne,t.nomtypeetablissement,e.nometabsco) LIKE ?','%'.$q.'%')
			//->orWhere('e.nometabsco LIKE ?','%'.$q.'%')
			//->orWhere('t.nomtypeetablissement LIKE ?', '%'.$q.'%')
			//->orWhere('t.nomtypeetablissement LIKE ?',$q)
			->limit($limit)
            ->orderBy('e.rne ASC');
    return $dq->execute();
  }
	
	public function getEtabscoBySecteur()
	{
		// condition l'user en cours est du groupe 'acad' 
		if(sfContext::getInstance()->getUser()->getGuardUser()->hasGroup('acad'))
		{
			// recherche du secteur de l'eleve en cours
			//$secteur = sfContext::getInstance()->getUser()->getAttribute('secteur_id');
			
			$q = Doctrine_Query::create()
					->select('e.id')
					->from('etabsco e')
					->orderBy('e.typeetablissement_id,e.nometabsco');
					//->innerJoin('secteur s')
					//->where('e.id IN (SELECT se.etabsco_id FROM SecteurEtabsco se WHERE secteur_id=?)', 2); // a changer
			//return $q;			
		}else{
			$userId = sfContext::getInstance()->getUser()->getGuardUser()->getId();
			$userSecteur = Doctrine::getTable('Secteur')->findBySfguarduserId($userId);
			$q = Doctrine_Query::create()
					->select('e.id')
					->from('etabsco e')
					//->innerJoin('secteur s')
					->where('e.id IN (SELECT se.etabsco_id FROM SecteurEtabsco se WHERE secteur_id=?)', $userSecteur[0]['id']);
			//return $q;
		}
		return $q;
		
	}
	
	public function ListEtab(){
    $dq = Doctrine_Query::create()
            ->select('e.id, e.rne,e.nometabsco,t.nomtypeetablissement')
            ->from('etabsco e')
			->innerjoin('e.Typeetablissement t on t.id = e.typeetablissement_id ')
            ->orderBy('e.rne ASC');
    return $dq->execute();
  }
}
