<?php

/**
 * InclusionEtabTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtabscoInclusionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InclusionEtabTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InclusionEtab');
    }
}
