<?php

/**
 * InclusionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InclusionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InclusionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inclusion');
    }
}