<?php

/**
 * MailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mail');
    }
}