<?php

/**
 * MarqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Marque');
    }
}