<?php

/**
 * MdphTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MdphTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MdphTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mdph');
    }
}