<?php

/**
 * Mdph
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ashile
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mdph extends BaseMdph
{
	public function DemandeComplet()
	{
		//cette fonction retourne dossier complet ou incomplet
		$aa = true;
		$a = Doctrine_Core::getTable('DemandeAvs')->findOneByMdphId($this->getId());		
		if($a){ 
			if($a->getDatedecisioncda()){
					$aa = true;			
			}else{$aa = false;}				
		}
		
  		$bb = true;
		$b = Doctrine_Core::getTable('Demandemateriel')->findOneByMdphId($this->getId());		
		if($b){ 
			if($b->getDatedecisioncda()){
				$bb = true;					
			}else{$bb = false;}				
		}

  		$cc = true;
		$c = Doctrine_Core::getTable('DemandeSessad')->findOneByMdphId($this->getId());		
		if($c){ 
			if($c->getDatedecisioncda()){
				$cc = true;					
			}else{$cc = false;}				
		}

  		$dd = true;
		$d = Doctrine_Core::getTable('Demandetransport')->findOneByMdphId($this->getId());		
		if($d){ 
			if($d->getDatedecisioncda()){
				$dd = true;					
			}else{$dd = false;}				
		}
		
		if($aa&&$bb&&$cc&&$dd){		
			return 'Toutes les demandes ont été traitée';
		}else{ return 'Il reste des demandes en attente de traitement';}
	}
	
		public function controleDelete()
		{
		 //-------- RECHERCHE DES DEMANDES LIEES A CE DOSSIER ----//
        //////////////////////////////////////////////////////////
         $message = '';
         $monTab = Array();
        
        // 1) demande transport ---------------------------------
        $dt = Doctrine_Query::Create()
				->select('dt.id as id, dt.decisioncda as cda')
				->from('DemandeTransport dt')
				->where('dt.mdph_id =?', $this->getId())
				->fetchArray();
	
		$monTab[] = Array($dt);
		
        // 2) demande sessad ------------------------------------
        $ds = Doctrine_Query::Create()
				->select('ds.id as id, ds.decisioncda as cda')
				->from('DemandeSessad ds')
				->where('ds.mdph_id =?', $this->getId())
				->fetchArray();
				
		$monTab[] = Array($ds);		
				        
        // 3) demandes avs ---------------------------------------
		$da = Doctrine_Query::Create()
				->select('da.id as id, da.decisioncda as cda')
				->from('DemandeAvs da')
				->where('da.mdph_id =?', $this->getId())
				->fetchArray();
				
		$monTab[] = Array($da); 		
        
        // 4) demandes materiels --------------------------------
        $dm = Doctrine_Query::Create()
				->select('dm.id as id, dm.decisioncda as cda')
				->from('DemandeMateriel dm')
				->where('dm.mdph_id =?', $this->getId())
				->fetchArray();
				
		$monTab[] = Array($dm); 		
				        
        // 5) demandes orientation ------------------------------
        $do = Doctrine_Query::Create()
				->select('do.id as id, do.decisioncda as cda')
				->from('DemandeOrientation do')
				->where('do.mdph_id =?', $this->getId())
				->fetchArray();
				
		$monTab[] = Array($do); 		
		
		
/*************** MODIF DU 25 mars 2014 ***************			
        // 6) bilans --------------------------------------------
        $bi = Doctrine_Query::Create()
				->select('bi.id as id')
				->from('Bilan bi')
				->where('bi.mdph_id =?', $this->getId())
				->fetchArray();
	
        // 7) pieces dossier ------------------------------------
        $pd = Doctrine_Query::Create()
				->select('pd.id as id')
				->from('PiecesDossier pd')
				->where('pd.mdph_id =?', $this->getId())
				->fetchArray();
*******************************************************/
		// --- recherche des demande avec cda acceptés : on ne peut pas effacer
		
		
		$message="";
		// 1) il y a au minimum une demande accepté pour ce dossier = suppression impossible 
		if($dt[0]['cda'] | $ds[0]['cda'] |$da[0]['cda'] |$dm[0]['cda'] |$do[0]['cda'])
		{
			$message = "Attention il existe au moins une demande accepté pa la CDA, impossible d'effacer le dossier" ;
		// 2) SINON il y a au minimum une demande enregistré pour ce dossier = commencer par supprimer toutes les demandes liées à ce dossier	
		}elseif($dm[0]['id']| $ds[0]['id'] |$da[0]['id'] |$dm[0]['id'] |$do[0]['id'])
		{
			 $message ="Attention veuillez commencer par supprimer les demandes liées à ce dossier";
		}	
			
		return $message;

		}
}
