<?php

/**
 * MessageAccueilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageAccueilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessageAccueilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MessageAccueil');
    }
}