<?php

/**
 * ModnonscoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModnonscoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModnonscoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Modnonsco');
    }
    
    public function getModnonsco1()
        {
           $annee = Doctrine_core::getTable('Anneescolaire')->getAnneeScolaireEnCours();
           $deb = $annee->getDatedebutanneescolaire();
           $fin = $annee->getDatefinanneescolaire();

            $q = Doctrine_query::create()
                                        ->from('Modnonsco a')
                                        ->where('a.eleve_id =?', $this->getRequestParameter('eleve_id'))
                                        ->andWhere('a.datedebut >=?',$deb )
                                        ->andWhere('a.datefin <=?', $fin);
            return $q->execute();
        }
		
	public function getDerModnonSco($eleve_id)
	{
			  //Dernière scolarisation en milieu spécialisé
			  //---------------------------------------------
	     
				$q = $this->createQuery('c')
               ->select('a.*,c.libelle_classe_spe as libelle_classe_spe,et.nometabnonsco as nometabnonsco,q.nom_quartier as nom_quartier,c.*,d.*')
               ->from('Modnonsco a')
               ->leftJoin('a.Etabnonsco et ON a.etabnonsco_id = et.id')
			   ->leftJoin('a.Classespe c ON a.classespe_id = c.id')
			   ->leftJoin('a.Demijournee d ON a.demijournee_id = d.id')
			   ->leftJoin('et.Quartier q ON et.quartier_id = q.id')
			   ->where('a.eleve_id = ?', $eleve_id)
			   ->andwhere('a.datedebut <=?',date('Y-m-d', time()))
			   ->andWhere('a.datefin IS NULL OR a.datefin >=?', date('Y-m-d', time()))
			   ->limit(1)
			    ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
			  	return $q->fetchArray();
									
	}
	
	
		public function getScoencour($eleve_id)
	{
			  //Scolarisation en milieu spécialisé en cour
			  //--------------------------------------------
	     
				$q = $this->createQuery('c')
										->select('*')
                                        ->from('Modnonsco a')
                                        ->where('a.eleve_id =?', $eleve_id)
 										->andwhere('a.datedebut <=?',date('Y-m-d', time()))
										->andWhere('a.datefin IS NULL OR a.datefin >=?', date('Y-m-d', time()));
   		 
			  	return $q->execute();
									
	}

}
