<?php

/**
 * MouvementMaterielTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MouvementMaterielTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MouvementMaterielTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MouvementMateriel');
    }
}