<?php

/**
 * NaturesuiviextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NaturesuiviextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NaturesuiviextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Naturesuiviext');
    }
}