<?php

/**
 * NaturecontratavsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NaturecontratavsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NaturecontratavsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Naturecontratavs');
    }
}