<?php

/**
 * NiveauscolaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NiveauscolaireTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NiveauscolaireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Niveauscolaire');
    }
    
	public function getExecniveau($etabId){
	// on recherche les niveauscolaires correspondant a l'etabsco selectionné//
	///////////////////////////////////////////////////////////////////////////
	
	// 1) //on cherche les classes///
	        $etab_sco = Doctrine_Query::create()
                        ->select ('*')
						 ->from('Etabsco e')
                        ->where( 'e.id = ?', $etabId )
                        ->fetchArray();
                        
            $q = Doctrine_Query::Create()
							->select('*')
							->from('Niveauscolaire n')
							->where('n.degreetabsco =? ', $etab_sco['degreetabsco'] );

        return $q->execute();
    
		}
    
}
