<?php

/**
 * NiveauscolairespeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NiveauscolairespeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NiveauscolairespeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Niveauscolairespe');
    }
    

    
}
