<?php

/**
 * OrganismeSuivitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganismeSuivitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganismeSuivitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganismeSuivit');
    }
	  public function getOrganismeValid($secteur)
    {
		return Doctrine_Query::Create()
			->from('OrganismeSuivit s')
			->where('s.secteur_id=?', $secteur->getId());
	} 
}