<?php

/**
 * positionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class positionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object positionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('position');
    }
}