<?php

/**
 * PositionAvsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PositionAvsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PositionAvsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PositionAvs');
    }
}