<?php

/**
 * PpsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PpsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PpsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pps');
    }
}