<?php

/**
 * RasedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RasedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RasedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rased');
    }
    

}
