<?php

/**
 * ReponseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReponseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReponseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reponse');
    }
}
