<?php

/**
 * ResponsableEleveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponsableEleveTable extends PersonneTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponsableEleveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResponsableEleve');
    }
}