<?php

/**
 * ReunionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReunionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReunionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reunion');
    }
	
		public function getDerReunionESS($eleveId)

	{
				$q =Doctrine_Query::Create()
				->select('r.typereunion_id as typereunion_id,r.id as reunion_id,t.libelletypereunion as libelletypereunion,r.datereunion as datereunion,r.libellereunion as libellereunion')
                -> from('Reunion r')
                ->innerJoin('r.TypeReunion t ON r.typereunion_id = t.id')
				->where('r.eleve_id=?',$eleveId)
				->andWhere('t.libelletypereunion  LIKE "%ESS%"')
			//	->groupby('r.typereunion_id')
			    ->orderby('r.datereunion desc');
				 return $q->fetchArray();
	}
	
	
			public function getDerReunion($eleveId)

	{
				$q =Doctrine_Query::Create()
				->select('r.typereunion_id as typereunion_id,r.id as reunion_id,t.libelletypereunion as libelletypereunion,r.datereunion as datereunion,r.libellereunion as libellereunion')
                -> from('Reunion r')
                ->innerJoin('r.TypeReunion t ON r.typereunion_id = t.id')
				->where('r.eleve_id=?',$eleveId)
			    ->orderby('r.datereunion desc')
				->limit(1);
				 return $q->fetchArray();
	}
}