<?php

/**
 * Secteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ash974
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Secteur extends BaseSecteur
{

	public function __toString()
	{
		return $this->getLibellesecteur();
	}
	
	public function getEtabscos()
    {
        $secteurEtabscos = $this->getSecteurEtabscos();
        $etabscos = array();
        foreach ($secteurEtabscos as $secteurEtabsco) {
            $etabscos[] = $secteurEtabsco->getEtabsco();
        }
        return $etabscos;
    }
}
