<?php

/**
 * SecteurEtabscoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SecteurEtabscoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SecteurEtabscoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SecteurEtabsco');
    }
	
}
