<?php

/**
 * SessadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SessadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SessadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sessad');
    }
}