<?php

/**
 * SessadobtenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SessadobtenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SessadobtenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sessadobtenu');
    }
	public function SessadaTraiter($secteur_id)
	{
	
		//liste des sessad alloués non traités
		//-----------------------------------------
				$res = Doctrine_Query::create()
                ->select('s.id as sessadobtenu_id,d.id as demandetransport_id,s.datedebut as datedebut,s.datefin as datefin,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,
				et.nometabnonsco as nometabnonsco,e.nom as nom,e.prenom as prenom,e.id as eleve_id,m.id as mdph_id,et.id as etabnonsco_id,a.id as sessad_id,a.typesessad_id as typesessad_id')
                ->from('SessadObtenu s')
                ->innerjoin('s.DemandeSessad d ON d.id = s.demandesessad_id')
			    ->innerjoin('s.Sessad a ON a.id = s.sessad_id')
				->innerjoin('a.Typesessad ty ON ty.id = a.typesessad_id')
		        ->innerjoin('a.Etabnonsco et ON et.id = a.etabnonsco_id')
				->innerjoin('d.Mdph m ON m.id = d.mdph_id')
				->innerjoin ('m.Eleve e ON e.id = m.eleve_id')
			//	->Where('et.nometabnonsco LIKE "%ND%" ');
				->where('s.datedebut is null')
				->andWhere('e.datesortie IS NULL or e.datesortie>=?', date('Y-m-d', time()))
			    ->andwhere('e.secteur_id =?', $secteur_id);
				
				return $res->fetchArray();
	}
	
		public function SessadaTraiterEleve($eleve_id)
	{
	
		    //liste des sessad alloués non traités pour l'élève selectionné
		   //------------------------------------------------------------------
				$res = Doctrine_Query::create()
                ->select('s.id as sessadobtenu_id,d.id as demandetransport_id,s.datedebut as datedebut,s.datefin as datefin,d.datedebutnotif as datedebutnotif,d.datefinnotif as datefinnotif,
				et.nometabnonsco as nometabnonsco,e.nom as nom,e.prenom as prenom,e.id as eleve_id,m.id as mdph_id,et.id as etabnonsco_id,a.id as sessad_id,a.typesessad_id as typesessad_id,ty.libelletypesessad as libelletypesessad')
                ->from('SessadObtenu s')
                ->innerjoin('s.DemandeSessad d ON d.id = s.demandesessad_id')
			    ->innerjoin('s.Sessad a ON a.id = s.sessad_id')
				->innerjoin('a.Typesessad ty ON ty.id = a.typesessad_id')
		        ->innerjoin('a.Etabnonsco et ON et.id = a.etabnonsco_id')
				->innerjoin('d.Mdph m ON m.id = d.mdph_id')
				->innerjoin ('m.Eleve e ON e.id = m.eleve_id')
				->where('m.eleve_id=?',$eleve_id)
			//	->AndWhere('et.nometabnonsco LIKE "%ND%" ');
				->andwhere('s.datedebut is null');

			
				
				return $res->fetchArray();
	}
}