<?php

/**
 * SituationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SituationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SituationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Situation');
    }
}