<?php

/**
 * SpecialisteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecialisteTable extends PersonneTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecialisteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Specialiste');
    }
    
   public function getSpecialisteValid($secteur)
    {
		return Doctrine_Query::Create()
			->from('Specialiste s')
			->where('s.secteur_id=?', $secteur->getId());
	} 

 }
