<?php

/**
 * Specialiste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Specialiste extends BaseSpecialiste
{
	
  static public function capitalize($field){  //mettre en majuscule
 setlocale(LC_CTYPE, 'fr_FR.UTF8');
return mb_strtoupper($field, 'UTF-8'); }

public function __toString()
	{
		return $this->getNom().' '.$this->getPrenom().'('.$this->getSpecialite().')';
	}
	

}
