<?php

/**
 * TraitementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TraitementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TraitementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Traitement');
    }
}