<?php

/**
 * TransportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Transport');
    }
}