<?php

/**
 * TroubleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TroubleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TroubleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trouble');
    }
}