<?php

/**
 * TuteurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TuteurTable extends PersonneTable {

    /**
     * Returns an instance of this class.
     *
     * @return object TuteurTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Tuteur');
    }

    public static function existTuteurLegals($eleveId) {
        // Eviter une erreur
        if ($eleveId == null)
            return false;
        $tuteurLegals = Doctrine_query::create()
                ->from('Tuteur tu')
                ->select('*')
                ->where('eleve_id=?', $eleveId)
                ->andWhere('tuteurlegal=1')
                ->execute();
        return $tuteurLegals;  // return un tableau, logiquement c'est un seul, mais par precaution, j'ai mis un tableau
    }

}
