<?php

/**
 * TypesessadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypesessadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypesessadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typesessad');
    }
}