<?php

/**
 * TypeReunion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ash
 * @subpackage model
 * @author     regis Gravant
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TypeReunion extends BaseTypeReunion
{
	public function __toString()
	{
		return $this->getLibelletypereunion(); 
	}
}
