<?php

/**
 * TypeContratAvsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeContratAvsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeContratAvsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeContratAvs');
    }
}