<?php

/**
 * TypeReunionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeReunionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeReunionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeReunion');
    }
}