<?php

/**
 * TypeClasseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeClasseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeClasseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeClasse');
    }
}