<?php

/**
 * TypeResponsableEleveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeResponsableEleveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeResponsableEleveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeResponsableEleve');
    }
}