<?php

/**
 * TypeetablissementnonscoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeetablissementnonscoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeetablissementnonscoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typeetablissementnonsco');
    }
}