<?php

/**
 * TypeetablissementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeetablissementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeetablissementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typeetablissement');
    }
}