generator:
  class: sfDoctrineGenerator
  param:
    model_class:           secteuretabsco
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          secteuretabsco
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:  
        title: Liste des établissements
        display: [secteur,etabsco]	  
      filter: 
        display: [secteur_id]	  
      form:    ~
      edit:    ~
      new:     ~
