<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/06/09 10:50:10
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'eref',
        1 => 'acad',
      ),
    ),
  ),
);
