<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('demande_avs', 'demande_avs_eleve_id_orientation_id', array(
             'name' => 'demande_avs_eleve_id_orientation_id',
             'local' => 'eleve_id',
             'foreign' => 'id',
             'foreignTable' => 'orientation',
             ));
        $this->createForeignKey('eleve_avs', 'eleve_avs_eleve_id_orientation_eleve_id', array(
             'name' => 'eleve_avs_eleve_id_orientation_eleve_id',
             'local' => 'eleve_id',
             'foreign' => 'eleve_id',
             'foreignTable' => 'orientation',
             ));
        $this->createForeignKey('materiel', 'materiel_mouvement_id_mouvement_materiel_id', array(
             'name' => 'materiel_mouvement_id_mouvement_materiel_id',
             'local' => 'mouvement_id',
             'foreign' => 'id',
             'foreignTable' => 'mouvement_materiel',
             ));
        $this->addIndex('demande_avs', 'demande_avs_eleve_id', array(
             'fields' => 
             array(
              0 => 'eleve_id',
             ),
             ));
        $this->addIndex('eleve_avs', 'eleve_avs_eleve_id', array(
             'fields' => 
             array(
              0 => 'eleve_id',
             ),
             ));
        $this->addIndex('materiel', 'materiel_mouvement_id', array(
             'fields' => 
             array(
              0 => 'mouvement_id',
             ),
             ));
        $this->addIndex('orientation', 'eleve_id', array(
             'fields' => 
             array(
              0 => 'eleve_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('demande_avs', 'demande_avs_eleve_id_orientation_id');
        $this->dropForeignKey('eleve_avs', 'eleve_avs_eleve_id_orientation_eleve_id');
        $this->dropForeignKey('materiel', 'materiel_mouvement_id_mouvement_materiel_id');
        $this->removeIndex('demande_avs', 'demande_avs_eleve_id', array(
             'fields' => 
             array(
              0 => 'eleve_id',
             ),
             ));
        $this->removeIndex('eleve_avs', 'eleve_avs_eleve_id', array(
             'fields' => 
             array(
              0 => 'eleve_id',
             ),
             ));
        $this->removeIndex('materiel', 'materiel_mouvement_id', array(
             'fields' => 
             array(
              0 => 'mouvement_id',
             ),
             ));
        $this->removeIndex('orientation', 'eleve_id', array(
             'fields' => 
             array(
              0 => 'eleve_id',
             ),
             ));
    }
}