<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('demande_avs', 'date_demande_avs', 'date', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('demande_avs', 'daterecepdemanderf', 'date', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}