generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfguardusergroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sfguardusergroup
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des utilisateurs par groupes
      filter:
        class: false 
      form:    ~
      edit:
        title: Edition des utilisateurs par groupes
      new:
        title: Création des utilisateurs par groupes
